import 'package:colornames/src/color_value_vo.dart';
import 'package:flutter/painting.dart';

abstract class ColorNamesList{
  static final namesMap = {
    ColorValueVo( Color(0xFF000000),) : "Black",
    ColorValueVo( Color(0xFF000080),) : "Navy Blue",
    ColorValueVo( Color(0xFF0000C8),) : "Dark Blue",
    ColorValueVo( Color(0xFF0000FF),) : "Blue",
    ColorValueVo( Color(0xFF000741),) : "Stratos",
    ColorValueVo( Color(0xFF001B1C),) : "Swamp",
    ColorValueVo( Color(0xFF002387),) : "Resolution Blue",
    ColorValueVo( Color(0xFF002900),) : "Deep Fir",
    ColorValueVo( Color(0xFF002E20),) : "Burnham",
    ColorValueVo( Color(0xFF002FA7),) : "International Klein Blue",
    ColorValueVo( Color(0xFF003153),) : "Prussian Blue",
    ColorValueVo( Color(0xFF003366),) : "Midnight Blue",
    ColorValueVo( Color(0xFF003399),) : "Smalt",
    ColorValueVo( Color(0xFF003532),) : "Deep Teal",
    ColorValueVo( Color(0xFF003E40),) : "Cyprus",
    ColorValueVo( Color(0xFF004620),) : "Kaitoke Green",
    ColorValueVo( Color(0xFF0047AB),) : "Cobalt",
    ColorValueVo( Color(0xFF004816),) : "Crusoe",
    ColorValueVo( Color(0xFF004950),) : "Sherpa Blue",
    ColorValueVo( Color(0xFF0056A7),) : "Endeavour",
    ColorValueVo( Color(0xFF00581A),) : "Camarone",
    ColorValueVo( Color(0xFF0066CC),) : "Science Blue",
    ColorValueVo( Color(0xFF0066FF),) : "Blue Ribbon",
    ColorValueVo( Color(0xFF00755E),) : "Tropical Rain Forest",
    ColorValueVo( Color(0xFF0076A3),) : "Allports",
    ColorValueVo( Color(0xFF007BA7),) : "Deep Cerulean",
    ColorValueVo( Color(0xFF007EC7),) : "Lochmara",
    ColorValueVo( Color(0xFF007FFF),) : "Azure Radiance",
    ColorValueVo( Color(0xFF008080),) : "Teal",
    ColorValueVo( Color(0xFF0095B6),) : "Bondi Blue",
    ColorValueVo( Color(0xFF009DC4),) : "Pacific Blue",
    ColorValueVo( Color(0xFF00A693),) : "Persian Green",
    ColorValueVo( Color(0xFF00A86B),) : "Jade",
    ColorValueVo( Color(0xFF00CC99),) : "Caribbean Green",
    ColorValueVo( Color(0xFF00CCCC),) : "Robin's Egg Blue",
    ColorValueVo( Color(0xFF00FF00),) : "Green",
    ColorValueVo( Color(0xFF00FF7F),) : "Spring Green",
    ColorValueVo( Color(0xFF00FFFF),) : "CyanAqua",
    ColorValueVo( Color(0xFF010D1A),) : "Blue Charcoal",
    ColorValueVo( Color(0xFF011635),) : "Midnight",
    ColorValueVo( Color(0xFF011D13),) : "Holly",
    ColorValueVo( Color(0xFF012731),) : "Daintree",
    ColorValueVo( Color(0xFF01361C),) : "Cardin Green",
    ColorValueVo( Color(0xFF01371A),) : "County Green",
    ColorValueVo( Color(0xFF013E62),) : "Astronaut Blue",
    ColorValueVo( Color(0xFF013F6A),) : "Regal Blue",
    ColorValueVo( Color(0xFF014B43),) : "Aqua Deep",
    ColorValueVo( Color(0xFF015E85),) : "Orient",
    ColorValueVo( Color(0xFF016162),) : "Blue Stone",
    ColorValueVo( Color(0xFF016D39),) : "Fun Green",
    ColorValueVo( Color(0xFF01796F),) : "Pine Green",
    ColorValueVo( Color(0xFF017987),) : "Blue Lagoon",
    ColorValueVo( Color(0xFF01826B),) : "Deep Sea",
    ColorValueVo( Color(0xFF01A368),) : "Green Haze",
    ColorValueVo( Color(0xFF022D15),) : "English Holly",
    ColorValueVo( Color(0xFF02402C),) : "Sherwood Green",
    ColorValueVo( Color(0xFF02478E),) : "Congress Blue",
    ColorValueVo( Color(0xFF024E46),) : "Evening Sea",
    ColorValueVo( Color(0xFF026395),) : "Bahama Blue",
    ColorValueVo( Color(0xFF02866F),) : "Observatory",
    ColorValueVo( Color(0xFF02A4D3),) : "Cerulean",
    ColorValueVo( Color(0xFF03163C),) : "Tangaroa",
    ColorValueVo( Color(0xFF032B52),) : "Green Vogue",
    ColorValueVo( Color(0xFF036A6E),) : "Mosque",
    ColorValueVo( Color(0xFF041004),) : "Midnight Moss",
    ColorValueVo( Color(0xFF041322),) : "Black Pearl",
    ColorValueVo( Color(0xFF042E4C),) : "Blue Whale",
    ColorValueVo( Color(0xFF044022),) : "Zuccini",
    ColorValueVo( Color(0xFF044259),) : "Teal Blue",
    ColorValueVo( Color(0xFF051040),) : "Deep Cove",
    ColorValueVo( Color(0xFF051657),) : "Gulf Blue",
    ColorValueVo( Color(0xFF055989),) : "Venice Blue",
    ColorValueVo( Color(0xFF056F57),) : "Watercourse",
    ColorValueVo( Color(0xFF062A78),) : "Catalina Blue",
    ColorValueVo( Color(0xFF063537),) : "Tiber",
    ColorValueVo( Color(0xFF069B81),) : "Gossamer",
    ColorValueVo( Color(0xFF06A189),) : "Niagara",
    ColorValueVo( Color(0xFF073A50),) : "Tarawera",
    ColorValueVo( Color(0xFF080110),) : "Jaguar",
    ColorValueVo( Color(0xFF081910),) : "Black Bean",
    ColorValueVo( Color(0xFF082567),) : "Deep Sapphire",
    ColorValueVo( Color(0xFF088370),) : "Elf Green",
    ColorValueVo( Color(0xFF08E8DE),) : "Bright Turquoise",
    ColorValueVo( Color(0xFF092256),) : "Downriver",
    ColorValueVo( Color(0xFF09230F),) : "Palm Green",
    ColorValueVo( Color(0xFF09255D),) : "Madison",
    ColorValueVo( Color(0xFF093624),) : "Bottle Green",
    ColorValueVo( Color(0xFF095859),) : "Deep Sea Green",
    ColorValueVo( Color(0xFF097F4B),) : "Salem",
    ColorValueVo( Color(0xFF0A001C),) : "Black Russian",
    ColorValueVo( Color(0xFF0A480D),) : "Dark Fern",
    ColorValueVo( Color(0xFF0A6906),) : "Japanese Laurel",
    ColorValueVo( Color(0xFF0A6F75),) : "Atoll",
    ColorValueVo( Color(0xFF0B0B0B),) : "Cod Gray",
    ColorValueVo( Color(0xFF0B0F08),) : "Marshland",
    ColorValueVo( Color(0xFF0B1107),) : "Gordons Green",
    ColorValueVo( Color(0xFF0B1304),) : "Black Forest",
    ColorValueVo( Color(0xFF0B6207),) : "San Felix",
    ColorValueVo( Color(0xFF0BDA51),) : "Malachite",
    ColorValueVo( Color(0xFF0C0B1D),) : "Ebony",
    ColorValueVo( Color(0xFF0C0D0F),) : "Woodsmoke",
    ColorValueVo( Color(0xFF0C1911),) : "Racing Green",
    ColorValueVo( Color(0xFF0C7A79),) : "Surfie Green",
    ColorValueVo( Color(0xFF0C8990),) : "Blue Chill",
    ColorValueVo( Color(0xFF0D0332),) : "Black Rock",
    ColorValueVo( Color(0xFF0D1117),) : "Bunker",
    ColorValueVo( Color(0xFF0D1C19),) : "Aztec",
    ColorValueVo( Color(0xFF0D2E1C),) : "Bush",
    ColorValueVo( Color(0xFF0E0E18),) : "Cinder",
    ColorValueVo( Color(0xFF0E2A30),) : "Firefly",
    ColorValueVo( Color(0xFF0F2D9E),) : "Torea Bay",
    ColorValueVo( Color(0xFF10121D),) : "Vulcan",
    ColorValueVo( Color(0xFF101405),) : "Green Waterloo",
    ColorValueVo( Color(0xFF105852),) : "Eden",
    ColorValueVo( Color(0xFF110C6C),) : "Arapawa",
    ColorValueVo( Color(0xFF120A8F),) : "Ultramarine",
    ColorValueVo( Color(0xFF123447),) : "Elephant",
    ColorValueVo( Color(0xFF126B40),) : "Jewel",
    ColorValueVo( Color(0xFF130000),) : "Diesel",
    ColorValueVo( Color(0xFF130A06),) : "Asphalt",
    ColorValueVo( Color(0xFF13264D),) : "Blue Zodiac",
    ColorValueVo( Color(0xFF134F19),) : "Parsley",
    ColorValueVo( Color(0xFF140600),) : "Nero",
    ColorValueVo( Color(0xFF1450AA),) : "Tory Blue",
    ColorValueVo( Color(0xFF151F4C),) : "Bunting",
    ColorValueVo( Color(0xFF1560BD),) : "Denim",
    ColorValueVo( Color(0xFF15736B),) : "Genoa",
    ColorValueVo( Color(0xFF161928),) : "Mirage",
    ColorValueVo( Color(0xFF161D10),) : "Hunter Green",
    ColorValueVo( Color(0xFF162A40),) : "Big Stone",
    ColorValueVo( Color(0xFF163222),) : "Celtic",
    ColorValueVo( Color(0xFF16322C),) : "Timber Green",
    ColorValueVo( Color(0xFF163531),) : "Gable Green",
    ColorValueVo( Color(0xFF171F04),) : "Pine Tree",
    ColorValueVo( Color(0xFF175579),) : "Chathams Blue",
    ColorValueVo( Color(0xFF182D09),) : "Deep Forest Green",
    ColorValueVo( Color(0xFF18587A),) : "Blumine",
    ColorValueVo( Color(0xFF19330E),) : "Palm Leaf",
    ColorValueVo( Color(0xFF193751),) : "Nile Blue",
    ColorValueVo( Color(0xFF1959A8),) : "Fun Blue",
    ColorValueVo( Color(0xFF1A1A68),) : "Lucky Point",
    ColorValueVo( Color(0xFF1AB385),) : "Mountain Meadow",
    ColorValueVo( Color(0xFF1B0245),) : "Tolopea",
    ColorValueVo( Color(0xFF1B1035),) : "Haiti",
    ColorValueVo( Color(0xFF1B127B),) : "Deep Koamaru",
    ColorValueVo( Color(0xFF1B1404),) : "Acadia",
    ColorValueVo( Color(0xFF1B2F11),) : "Seaweed",
    ColorValueVo( Color(0xFF1B3162),) : "Biscay",
    ColorValueVo( Color(0xFF1B659D),) : "Matisse",
    ColorValueVo( Color(0xFF1C1208),) : "Crowshead",
    ColorValueVo( Color(0xFF1C1E13),) : "Rangoon Green",
    ColorValueVo( Color(0xFF1C39BB),) : "Persian Blue",
    ColorValueVo( Color(0xFF1C402E),) : "Everglade",
    ColorValueVo( Color(0xFF1C7C7D),) : "Elm",
    ColorValueVo( Color(0xFF1D6142),) : "Green Pea",
    ColorValueVo( Color(0xFF1E0F04),) : "Creole",
    ColorValueVo( Color(0xFF1E1609),) : "Karaka",
    ColorValueVo( Color(0xFF1E1708),) : "El Paso",
    ColorValueVo( Color(0xFF1E385B),) : "Cello",
    ColorValueVo( Color(0xFF1E433C),) : "Te Papa Green",
    ColorValueVo( Color(0xFF1E90FF),) : "Dodger Blue",
    ColorValueVo( Color(0xFF1E9AB0),) : "Eastern Blue",
    ColorValueVo( Color(0xFF1F120F),) : "Night Rider",
    ColorValueVo( Color(0xFF1FC2C2),) : "Java",
    ColorValueVo( Color(0xFF20208D),) : "Jacksons Purple",
    ColorValueVo( Color(0xFF202E54),) : "Cloud Burst",
    ColorValueVo( Color(0xFF204852),) : "Blue Dianne",
    ColorValueVo( Color(0xFF211A0E),) : "Eternity",
    ColorValueVo( Color(0xFF220878),) : "Deep Blue",
    ColorValueVo( Color(0xFF228B22),) : "Forest Green",
    ColorValueVo( Color(0xFF233418),) : "Mallard",
    ColorValueVo( Color(0xFF240A40),) : "Violet",
    ColorValueVo( Color(0xFF240C02),) : "Kilamanjaro",
    ColorValueVo( Color(0xFF242A1D),) : "Log Cabin",
    ColorValueVo( Color(0xFF242E16),) : "Black Olive",
    ColorValueVo( Color(0xFF24500F),) : "Green House",
    ColorValueVo( Color(0xFF251607),) : "Graphite",
    ColorValueVo( Color(0xFF251706),) : "Cannon Black",
    ColorValueVo( Color(0xFF251F4F),) : "Port Gore",
    ColorValueVo( Color(0xFF25272C),) : "Shark",
    ColorValueVo( Color(0xFF25311C),) : "Green Kelp",
    ColorValueVo( Color(0xFF2596D1),) : "Curious Blue",
    ColorValueVo( Color(0xFF260368),) : "Paua",
    ColorValueVo( Color(0xFF26056A),) : "Paris M",
    ColorValueVo( Color(0xFF261105),) : "Wood Bark",
    ColorValueVo( Color(0xFF261414),) : "Gondola",
    ColorValueVo( Color(0xFF262335),) : "Steel Gray",
    ColorValueVo( Color(0xFF26283B),) : "Ebony Clay",
    ColorValueVo( Color(0xFF273A81),) : "Bay of Many",
    ColorValueVo( Color(0xFF27504B),) : "Plantation",
    ColorValueVo( Color(0xFF278A5B),) : "Eucalyptus",
    ColorValueVo( Color(0xFF281E15),) : "Oil",
    ColorValueVo( Color(0xFF283A77),) : "Astronaut",
    ColorValueVo( Color(0xFF286ACD),) : "Mariner",
    ColorValueVo( Color(0xFF290C5E),) : "Violent Violet",
    ColorValueVo( Color(0xFF292130),) : "Bastille",
    ColorValueVo( Color(0xFF292319),) : "Zeus",
    ColorValueVo( Color(0xFF292937),) : "Charade",
    ColorValueVo( Color(0xFF297B9A),) : "Jelly Bean",
    ColorValueVo( Color(0xFF29AB87),) : "Jungle Green",
    ColorValueVo( Color(0xFF2A0359),) : "Cherry Pie",
    ColorValueVo( Color(0xFF2A140E),) : "Coffee Bean",
    ColorValueVo( Color(0xFF2A2630),) : "Baltic Sea",
    ColorValueVo( Color(0xFF2A380B),) : "Turtle Green",
    ColorValueVo( Color(0xFF2A52BE),) : "Cerulean Blue",
    ColorValueVo( Color(0xFF2B0202),) : "Sepia Black",
    ColorValueVo( Color(0xFF2B194F),) : "Valhalla",
    ColorValueVo( Color(0xFF2B3228),) : "Heavy Metal",
    ColorValueVo( Color(0xFF2C0E8C),) : "Blue Gem",
    ColorValueVo( Color(0xFF2C1632),) : "Revolver",
    ColorValueVo( Color(0xFF2C2133),) : "Bleached Cedar",
    ColorValueVo( Color(0xFF2C8C84),) : "Lochinvar",
    ColorValueVo( Color(0xFF2D2510),) : "Mikado",
    ColorValueVo( Color(0xFF2D383A),) : "Outer Space",
    ColorValueVo( Color(0xFF2D569B),) : "St Tropaz",
    ColorValueVo( Color(0xFF2E0329),) : "Jacaranda",
    ColorValueVo( Color(0xFF2E1905),) : "Jacko Bean",
    ColorValueVo( Color(0xFF2E3222),) : "Rangitoto",
    ColorValueVo( Color(0xFF2E3F62),) : "Rhino",
    ColorValueVo( Color(0xFF2E8B57),) : "Sea Green",
    ColorValueVo( Color(0xFF2EBFD4),) : "Scooter",
    ColorValueVo( Color(0xFF2F270E),) : "Onion",
    ColorValueVo( Color(0xFF2F3CB3),) : "Governor Bay",
    ColorValueVo( Color(0xFF2F519E),) : "Sapphire",
    ColorValueVo( Color(0xFF2F5A57),) : "Spectra",
    ColorValueVo( Color(0xFF2F6168),) : "Casal",
    ColorValueVo( Color(0xFF300529),) : "Melanzane",
    ColorValueVo( Color(0xFF301F1E),) : "Cocoa Brown",
    ColorValueVo( Color(0xFF302A0F),) : "Woodrush",
    ColorValueVo( Color(0xFF304B6A),) : "San Juan",
    ColorValueVo( Color(0xFF30D5C8),) : "Turquoise",
    ColorValueVo( Color(0xFF311C17),) : "Eclipse",
    ColorValueVo( Color(0xFF314459),) : "Pickled Bluewood",
    ColorValueVo( Color(0xFF315BA1),) : "Azure",
    ColorValueVo( Color(0xFF31728D),) : "Calypso",
    ColorValueVo( Color(0xFF317D82),) : "Paradiso",
    ColorValueVo( Color(0xFF32127A),) : "Persian Indigo",
    ColorValueVo( Color(0xFF32293A),) : "Blackcurrant",
    ColorValueVo( Color(0xFF323232),) : "Mine Shaft",
    ColorValueVo( Color(0xFF325D52),) : "Stromboli",
    ColorValueVo( Color(0xFF327C14),) : "Bilbao",
    ColorValueVo( Color(0xFF327DA0),) : "Astral",
    ColorValueVo( Color(0xFF33036B),) : "Christalle",
    ColorValueVo( Color(0xFF33292F),) : "Thunder",
    ColorValueVo( Color(0xFF33CC99),) : "Shamrock",
    ColorValueVo( Color(0xFF341515),) : "Tamarind",
    ColorValueVo( Color(0xFF350036),) : "Mardi Gras",
    ColorValueVo( Color(0xFF350E42),) : "Valentino",
    ColorValueVo( Color(0xFF350E57),) : "Jagger",
    ColorValueVo( Color(0xFF353542),) : "Tuna",
    ColorValueVo( Color(0xFF354E8C),) : "Chambray",
    ColorValueVo( Color(0xFF363050),) : "Martinique",
    ColorValueVo( Color(0xFF363534),) : "Tuatara",
    ColorValueVo( Color(0xFF363C0D),) : "Waiouru",
    ColorValueVo( Color(0xFF36747D),) : "Ming",
    ColorValueVo( Color(0xFF368716),) : "La Palma",
    ColorValueVo( Color(0xFF370202),) : "Chocolate",
    ColorValueVo( Color(0xFF371D09),) : "Clinker",
    ColorValueVo( Color(0xFF37290E),) : "Brown Tumbleweed",
    ColorValueVo( Color(0xFF373021),) : "Birch",
    ColorValueVo( Color(0xFF377475),) : "Oracle",
    ColorValueVo( Color(0xFF380474),) : "Blue Diamond",
    ColorValueVo( Color(0xFF381A51),) : "Grape",
    ColorValueVo( Color(0xFF383533),) : "Dune",
    ColorValueVo( Color(0xFF384555),) : "Oxford Blue",
    ColorValueVo( Color(0xFF384910),) : "Clover",
    ColorValueVo( Color(0xFF394851),) : "Limed Spruce",
    ColorValueVo( Color(0xFF396413),) : "Dell",
    ColorValueVo( Color(0xFF3A0020),) : "Toledo",
    ColorValueVo( Color(0xFF3A2010),) : "Sambuca",
    ColorValueVo( Color(0xFF3A2A6A),) : "Jacarta",
    ColorValueVo( Color(0xFF3A686C),) : "William",
    ColorValueVo( Color(0xFF3A6A47),) : "Killarney",
    ColorValueVo( Color(0xFF3AB09E),) : "Keppel",
    ColorValueVo( Color(0xFF3B000B),) : "Temptress",
    ColorValueVo( Color(0xFF3B0910),) : "Aubergine",
    ColorValueVo( Color(0xFF3B1F1F),) : "Jon",
    ColorValueVo( Color(0xFF3B2820),) : "Treehouse",
    ColorValueVo( Color(0xFF3B7A57),) : "Amazon",
    ColorValueVo( Color(0xFF3B91B4),) : "Boston Blue",
    ColorValueVo( Color(0xFF3C0878),) : "Windsor",
    ColorValueVo( Color(0xFF3C1206),) : "Rebel",
    ColorValueVo( Color(0xFF3C1F76),) : "Meteorite",
    ColorValueVo( Color(0xFF3C2005),) : "Dark Ebony",
    ColorValueVo( Color(0xFF3C3910),) : "Camouflage",
    ColorValueVo( Color(0xFF3C4151),) : "Bright Gray",
    ColorValueVo( Color(0xFF3C4443),) : "Cape Cod",
    ColorValueVo( Color(0xFF3C493A),) : "Lunar Green",
    ColorValueVo( Color(0xFF3D0C02),) : "Bean",
    ColorValueVo( Color(0xFF3D2B1F),) : "Bistre",
    ColorValueVo( Color(0xFF3D7D52),) : "Goblin",
    ColorValueVo( Color(0xFF3E0480),) : "Kingfisher Daisy",
    ColorValueVo( Color(0xFF3E1C14),) : "Cedar",
    ColorValueVo( Color(0xFF3E2B23),) : "English Walnut",
    ColorValueVo( Color(0xFF3E2C1C),) : "Black Marlin",
    ColorValueVo( Color(0xFF3E3A44),) : "Ship Gray",
    ColorValueVo( Color(0xFF3EABBF),) : "Pelorous",
    ColorValueVo( Color(0xFF3F2109),) : "Bronze",
    ColorValueVo( Color(0xFF3F2500),) : "Cola",
    ColorValueVo( Color(0xFF3F3002),) : "Madras",
    ColorValueVo( Color(0xFF3F307F),) : "Minsk",
    ColorValueVo( Color(0xFF3F4C3A),) : "Cabbage Pont",
    ColorValueVo( Color(0xFF3F583B),) : "Tom Thumb",
    ColorValueVo( Color(0xFF3F5D53),) : "Mineral Green",
    ColorValueVo( Color(0xFF3FC1AA),) : "Puerto Rico",
    ColorValueVo( Color(0xFF3FFF00),) : "Harlequin",
    ColorValueVo( Color(0xFF401801),) : "Brown Pod",
    ColorValueVo( Color(0xFF40291D),) : "Cork",
    ColorValueVo( Color(0xFF403B38),) : "Masala",
    ColorValueVo( Color(0xFF403D19),) : "Thatch Green",
    ColorValueVo( Color(0xFF405169),) : "Fiord",
    ColorValueVo( Color(0xFF40826D),) : "Viridian",
    ColorValueVo( Color(0xFF40A860),) : "Chateau Green",
    ColorValueVo( Color(0xFF410056),) : "Ripe Plum",
    ColorValueVo( Color(0xFF411F10),) : "Paco",
    ColorValueVo( Color(0xFF412010),) : "Deep Oak",
    ColorValueVo( Color(0xFF413C37),) : "Merlin",
    ColorValueVo( Color(0xFF414257),) : "Gun Powder",
    ColorValueVo( Color(0xFF414C7D),) : "East Bay",
    ColorValueVo( Color(0xFF4169E1),) : "Royal Blue",
    ColorValueVo( Color(0xFF41AA78),) : "Ocean Green",
    ColorValueVo( Color(0xFF420303),) : "Burnt Maroon",
    ColorValueVo( Color(0xFF423921),) : "Lisbon Brown",
    ColorValueVo( Color(0xFF427977),) : "Faded Jade",
    ColorValueVo( Color(0xFF431560),) : "Scarlet Gum",
    ColorValueVo( Color(0xFF433120),) : "Iroko",
    ColorValueVo( Color(0xFF433E37),) : "Armadillo",
    ColorValueVo( Color(0xFF434C59),) : "River Bed",
    ColorValueVo( Color(0xFF436A0D),) : "Green Leaf",
    ColorValueVo( Color(0xFF44012D),) : "Barossa",
    ColorValueVo( Color(0xFF441D00),) : "Morocco Brown",
    ColorValueVo( Color(0xFF444954),) : "Mako",
    ColorValueVo( Color(0xFF454936),) : "Kelp",
    ColorValueVo( Color(0xFF456CAC),) : "San Marino",
    ColorValueVo( Color(0xFF45B1E8),) : "Picton Blue",
    ColorValueVo( Color(0xFF460B41),) : "Loulou",
    ColorValueVo( Color(0xFF462425),) : "Crater Brown",
    ColorValueVo( Color(0xFF465945),) : "Gray Asparagus",
    ColorValueVo( Color(0xFF4682B4),) : "Steel Blue",
    ColorValueVo( Color(0xFF480404),) : "Rustic Red",
    ColorValueVo( Color(0xFF480607),) : "Bulgarian Rose",
    ColorValueVo( Color(0xFF480656),) : "Clairvoyant",
    ColorValueVo( Color(0xFF481C1C),) : "Cocoa Bean",
    ColorValueVo( Color(0xFF483131),) : "Woody Brown",
    ColorValueVo( Color(0xFF483C32),) : "Taupe",
    ColorValueVo( Color(0xFF49170C),) : "Van Cleef",
    ColorValueVo( Color(0xFF492615),) : "Brown Derby",
    ColorValueVo( Color(0xFF49371B),) : "Metallic Bronze",
    ColorValueVo( Color(0xFF495400),) : "Verdun Green",
    ColorValueVo( Color(0xFF496679),) : "Blue Bayoux",
    ColorValueVo( Color(0xFF497183),) : "Bismark",
    ColorValueVo( Color(0xFF4A2A04),) : "Bracken",
    ColorValueVo( Color(0xFF4A3004),) : "Deep Bronze",
    ColorValueVo( Color(0xFF4A3C30),) : "Mondo",
    ColorValueVo( Color(0xFF4A4244),) : "Tundora",
    ColorValueVo( Color(0xFF4A444B),) : "Gravel",
    ColorValueVo( Color(0xFF4A4E5A),) : "Trout",
    ColorValueVo( Color(0xFF4B0082),) : "Pigment Indigo",
    ColorValueVo( Color(0xFF4B5D52),) : "Nandor",
    ColorValueVo( Color(0xFF4C3024),) : "Saddle",
    ColorValueVo( Color(0xFF4C4F56),) : "Abbey",
    ColorValueVo( Color(0xFF4D0135),) : "Blackberry",
    ColorValueVo( Color(0xFF4D0A18),) : "Cab Sav",
    ColorValueVo( Color(0xFF4D1E01),) : "Indian Tan",
    ColorValueVo( Color(0xFF4D282D),) : "Cowboy",
    ColorValueVo( Color(0xFF4D282E),) : "Livid Brown",
    ColorValueVo( Color(0xFF4D3833),) : "Rock",
    ColorValueVo( Color(0xFF4D3D14),) : "Punga",
    ColorValueVo( Color(0xFF4D400F),) : "Bronzetone",
    ColorValueVo( Color(0xFF4D5328),) : "Woodland",
    ColorValueVo( Color(0xFF4E0606),) : "Mahogany",
    ColorValueVo( Color(0xFF4E2A5A),) : "Bossanova",
    ColorValueVo( Color(0xFF4E3B41),) : "Matterhorn",
    ColorValueVo( Color(0xFF4E420C),) : "Bronze Olive",
    ColorValueVo( Color(0xFF4E4562),) : "Mulled Wine",
    ColorValueVo( Color(0xFF4E6649),) : "Axolotl",
    ColorValueVo( Color(0xFF4E7F9E),) : "Wedgewood",
    ColorValueVo( Color(0xFF4EABD1),) : "Shakespeare",
    ColorValueVo( Color(0xFF4F1C70),) : "Honey Flower",
    ColorValueVo( Color(0xFF4F2398),) : "Daisy Bush",
    ColorValueVo( Color(0xFF4F69C6),) : "Indigo",
    ColorValueVo( Color(0xFF4F7942),) : "Fern Green",
    ColorValueVo( Color(0xFF4F9D5D),) : "Fruit Salad",
    ColorValueVo( Color(0xFF4FA83D),) : "Apple",
    ColorValueVo( Color(0xFF504351),) : "Mortar",
    ColorValueVo( Color(0xFF507096),) : "Kashmir Blue",
    ColorValueVo( Color(0xFF507672),) : "Cutty Sark",
    ColorValueVo( Color(0xFF50C878),) : "Emerald",
    ColorValueVo( Color(0xFF514649),) : "Emperor",
    ColorValueVo( Color(0xFF516E3D),) : "Chalet Green",
    ColorValueVo( Color(0xFF517C66),) : "Como",
    ColorValueVo( Color(0xFF51808F),) : "Smalt Blue",
    ColorValueVo( Color(0xFF52001F),) : "Castro",
    ColorValueVo( Color(0xFF520C17),) : "Maroon Oak",
    ColorValueVo( Color(0xFF523C94),) : "Gigas",
    ColorValueVo( Color(0xFF533455),) : "Voodoo",
    ColorValueVo( Color(0xFF534491),) : "Victoria",
    ColorValueVo( Color(0xFF53824B),) : "Hippie Green",
    ColorValueVo( Color(0xFF541012),) : "Heath",
    ColorValueVo( Color(0xFF544333),) : "Judge Gray",
    ColorValueVo( Color(0xFF54534D),) : "Fuscous Gray",
    ColorValueVo( Color(0xFF549019),) : "Vida Loca",
    ColorValueVo( Color(0xFF55280C),) : "Cioccolato",
    ColorValueVo( Color(0xFF555B10),) : "Saratoga",
    ColorValueVo( Color(0xFF556D56),) : "Finlandia",
    ColorValueVo( Color(0xFF5590D9),) : "Havelock Blue",
    ColorValueVo( Color(0xFF56B4BE),) : "Fountain Blue",
    ColorValueVo( Color(0xFF578363),) : "Spring Leaves",
    ColorValueVo( Color(0xFF583401),) : "Saddle Brown",
    ColorValueVo( Color(0xFF585562),) : "Scarpa Flow",
    ColorValueVo( Color(0xFF587156),) : "Cactus",
    ColorValueVo( Color(0xFF589AAF),) : "Hippie Blue",
    ColorValueVo( Color(0xFF591D35),) : "Wine Berry",
    ColorValueVo( Color(0xFF592804),) : "Brown Bramble",
    ColorValueVo( Color(0xFF593737),) : "Congo Brown",
    ColorValueVo( Color(0xFF594433),) : "Millbrook",
    ColorValueVo( Color(0xFF5A6E9C),) : "Waikawa Gray",
    ColorValueVo( Color(0xFF5A87A0),) : "Horizon",
    ColorValueVo( Color(0xFF5B3013),) : "Jambalaya",
    ColorValueVo( Color(0xFF5C0120),) : "Bordeaux",
    ColorValueVo( Color(0xFF5C0536),) : "Mulberry Wood",
    ColorValueVo( Color(0xFF5C2E01),) : "Carnaby Tan",
    ColorValueVo( Color(0xFF5C5D75),) : "Comet",
    ColorValueVo( Color(0xFF5D1E0F),) : "Redwood",
    ColorValueVo( Color(0xFF5D4C51),) : "Don Juan",
    ColorValueVo( Color(0xFF5D5C58),) : "Chicago",
    ColorValueVo( Color(0xFF5D5E37),) : "Verdigris",
    ColorValueVo( Color(0xFF5D7747),) : "Dingley",
    ColorValueVo( Color(0xFF5DA19F),) : "Breaker Bay",
    ColorValueVo( Color(0xFF5E483E),) : "Kabul",
    ColorValueVo( Color(0xFF5E5D3B),) : "Hemlock",
    ColorValueVo( Color(0xFF5F3D26),) : "Irish Coffee",
    ColorValueVo( Color(0xFF5F5F6E),) : "Mid Gray",
    ColorValueVo( Color(0xFF5F6672),) : "Shuttle Gray",
    ColorValueVo( Color(0xFF5FA777),) : "Aqua Forest",
    ColorValueVo( Color(0xFF5FB3AC),) : "Tradewind",
    ColorValueVo( Color(0xFF604913),) : "Horses Neck",
    ColorValueVo( Color(0xFF605B73),) : "Smoky",
    ColorValueVo( Color(0xFF606E68),) : "Corduroy",
    ColorValueVo( Color(0xFF6093D1),) : "Danube",
    ColorValueVo( Color(0xFF612718),) : "Espresso",
    ColorValueVo( Color(0xFF614051),) : "Eggplant",
    ColorValueVo( Color(0xFF615D30),) : "Costa Del Sol",
    ColorValueVo( Color(0xFF61845F),) : "Glade Green",
    ColorValueVo( Color(0xFF622F30),) : "Buccaneer",
    ColorValueVo( Color(0xFF623F2D),) : "Quincy",
    ColorValueVo( Color(0xFF624E9A),) : "Butterfly Bush",
    ColorValueVo( Color(0xFF625119),) : "West Coast",
    ColorValueVo( Color(0xFF626649),) : "Finch",
    ColorValueVo( Color(0xFF639A8F),) : "Patina",
    ColorValueVo( Color(0xFF63B76C),) : "Fern",
    ColorValueVo( Color(0xFF6456B7),) : "Blue Violet",
    ColorValueVo( Color(0xFF646077),) : "Dolphin",
    ColorValueVo( Color(0xFF646463),) : "Storm Dust",
    ColorValueVo( Color(0xFF646A54),) : "Siam",
    ColorValueVo( Color(0xFF646E75),) : "Nevada",
    ColorValueVo( Color(0xFF6495ED),) : "Cornflower Blue",
    ColorValueVo( Color(0xFF64CCDB),) : "Viking",
    ColorValueVo( Color(0xFF65000B),) : "Rosewood",
    ColorValueVo( Color(0xFF651A14),) : "Cherrywood",
    ColorValueVo( Color(0xFF652DC1),) : "Purple Heart",
    ColorValueVo( Color(0xFF657220),) : "Fern Frond",
    ColorValueVo( Color(0xFF65745D),) : "Willow Grove",
    ColorValueVo( Color(0xFF65869F),) : "Hoki",
    ColorValueVo( Color(0xFF660045),) : "Pompadour",
    ColorValueVo( Color(0xFF660099),) : "Purple",
    ColorValueVo( Color(0xFF66023C),) : "Tyrian Purple",
    ColorValueVo( Color(0xFF661010),) : "Dark Tan",
    ColorValueVo( Color(0xFF66B58F),) : "Silver Tree",
    ColorValueVo( Color(0xFF66FF00),) : "Bright Green",
    ColorValueVo( Color(0xFF66FF66),) : "Screamin' Green",
    ColorValueVo( Color(0xFF67032D),) : "Black Rose",
    ColorValueVo( Color(0xFF675FA6),) : "Scampi",
    ColorValueVo( Color(0xFF676662),) : "Ironside Gray",
    ColorValueVo( Color(0xFF678975),) : "Viridian Green",
    ColorValueVo( Color(0xFF67A712),) : "Christi",
    ColorValueVo( Color(0xFF683600),) : "Nutmeg Wood Finish",
    ColorValueVo( Color(0xFF685558),) : "Zambezi",
    ColorValueVo( Color(0xFF685E6E),) : "Salt Box",
    ColorValueVo( Color(0xFF692545),) : "Tawny Port",
    ColorValueVo( Color(0xFF692D54),) : "Finn",
    ColorValueVo( Color(0xFF695F62),) : "Scorpion",
    ColorValueVo( Color(0xFF697E9A),) : "Lynch",
    ColorValueVo( Color(0xFF6A442E),) : "Spice",
    ColorValueVo( Color(0xFF6A5D1B),) : "Himalaya",
    ColorValueVo( Color(0xFF6A6051),) : "Soya Bean",
    ColorValueVo( Color(0xFF6B2A14),) : "Hairy Heath",
    ColorValueVo( Color(0xFF6B3FA0),) : "Royal Purple",
    ColorValueVo( Color(0xFF6B4E31),) : "Shingle Fawn",
    ColorValueVo( Color(0xFF6B5755),) : "Dorado",
    ColorValueVo( Color(0xFF6B8BA2),) : "Bermuda Gray",
    ColorValueVo( Color(0xFF6B8E23),) : "Olive Drab",
    ColorValueVo( Color(0xFF6C3082),) : "Eminence",
    ColorValueVo( Color(0xFF6CDAE7),) : "Turquoise Blue",
    ColorValueVo( Color(0xFF6D0101),) : "Lonestar",
    ColorValueVo( Color(0xFF6D5E54),) : "Pine Cone",
    ColorValueVo( Color(0xFF6D6C6C),) : "Dove Gray",
    ColorValueVo( Color(0xFF6D9292),) : "Juniper",
    ColorValueVo( Color(0xFF6D92A1),) : "Gothic",
    ColorValueVo( Color(0xFF6E0902),) : "Red Oxide",
    ColorValueVo( Color(0xFF6E1D14),) : "Moccaccino",
    ColorValueVo( Color(0xFF6E4826),) : "Pickled Bean",
    ColorValueVo( Color(0xFF6E4B26),) : "Dallas",
    ColorValueVo( Color(0xFF6E6D57),) : "Kokoda",
    ColorValueVo( Color(0xFF6E7783),) : "Pale Sky",
    ColorValueVo( Color(0xFF6F440C),) : "Cafe Royale",
    ColorValueVo( Color(0xFF6F6A61),) : "Flint",
    ColorValueVo( Color(0xFF6F8E63),) : "Highland",
    ColorValueVo( Color(0xFF6F9D02),) : "Limeade",
    ColorValueVo( Color(0xFF6FD0C5),) : "Downy",
    ColorValueVo( Color(0xFF701C1C),) : "Persian Plum",
    ColorValueVo( Color(0xFF704214),) : "Sepia",
    ColorValueVo( Color(0xFF704A07),) : "Antique Bronze",
    ColorValueVo( Color(0xFF704F50),) : "Ferra",
    ColorValueVo( Color(0xFF706555),) : "Coffee",
    ColorValueVo( Color(0xFF708090),) : "Slate Gray",
    ColorValueVo( Color(0xFF711A00),) : "Cedar Wood Finish",
    ColorValueVo( Color(0xFF71291D),) : "Metallic Copper",
    ColorValueVo( Color(0xFF714693),) : "Affair",
    ColorValueVo( Color(0xFF714AB2),) : "Studio",
    ColorValueVo( Color(0xFF715D47),) : "Tobacco Brown",
    ColorValueVo( Color(0xFF716338),) : "Yellow Metal",
    ColorValueVo( Color(0xFF716B56),) : "Peat",
    ColorValueVo( Color(0xFF716E10),) : "Olivetone",
    ColorValueVo( Color(0xFF717486),) : "Storm Gray",
    ColorValueVo( Color(0xFF718080),) : "Sirocco",
    ColorValueVo( Color(0xFF71D9E2),) : "Aquamarine Blue",
    ColorValueVo( Color(0xFF72010F),) : "Venetian Red",
    ColorValueVo( Color(0xFF724A2F),) : "Old Copper",
    ColorValueVo( Color(0xFF726D4E),) : "Go Ben",
    ColorValueVo( Color(0xFF727B89),) : "Raven",
    ColorValueVo( Color(0xFF731E8F),) : "Seance",
    ColorValueVo( Color(0xFF734A12),) : "Raw Umber",
    ColorValueVo( Color(0xFF736C9F),) : "Kimberly",
    ColorValueVo( Color(0xFF736D58),) : "Crocodile",
    ColorValueVo( Color(0xFF737829),) : "Crete",
    ColorValueVo( Color(0xFF738678),) : "Xanadu",
    ColorValueVo( Color(0xFF74640D),) : "Spicy Mustard",
    ColorValueVo( Color(0xFF747D63),) : "Limed Ash",
    ColorValueVo( Color(0xFF747D83),) : "Rolling Stone",
    ColorValueVo( Color(0xFF748881),) : "Blue Smoke",
    ColorValueVo( Color(0xFF749378),) : "Laurel",
    ColorValueVo( Color(0xFF74C365),) : "Mantis",
    ColorValueVo( Color(0xFF755A57),) : "Russett",
    ColorValueVo( Color(0xFF7563A8),) : "Deluge",
    ColorValueVo( Color(0xFF76395D),) : "Cosmic",
    ColorValueVo( Color(0xFF7666C6),) : "Blue Marguerite",
    ColorValueVo( Color(0xFF76BD17),) : "Lima",
    ColorValueVo( Color(0xFF76D7EA),) : "Sky Blue",
    ColorValueVo( Color(0xFF770F05),) : "Dark Burgundy",
    ColorValueVo( Color(0xFF771F1F),) : "Crown of Thorns",
    ColorValueVo( Color(0xFF773F1A),) : "Walnut",
    ColorValueVo( Color(0xFF776F61),) : "Pablo",
    ColorValueVo( Color(0xFF778120),) : "Pacifika",
    ColorValueVo( Color(0xFF779E86),) : "Oxley",
    ColorValueVo( Color(0xFF77DD77),) : "Pastel Green",
    ColorValueVo( Color(0xFF780109),) : "Japanese Maple",
    ColorValueVo( Color(0xFF782D19),) : "Mocha",
    ColorValueVo( Color(0xFF782F16),) : "Peanut",
    ColorValueVo( Color(0xFF78866B),) : "Camouflage Green",
    ColorValueVo( Color(0xFF788A25),) : "Wasabi",
    ColorValueVo( Color(0xFF788BBA),) : "Ship Cove",
    ColorValueVo( Color(0xFF78A39C),) : "Sea Nymph",
    ColorValueVo( Color(0xFF795D4C),) : "Roman Coffee",
    ColorValueVo( Color(0xFF796878),) : "Old Lavender",
    ColorValueVo( Color(0xFF796989),) : "Rum",
    ColorValueVo( Color(0xFF796A78),) : "Fedora",
    ColorValueVo( Color(0xFF796D62),) : "Sandstone",
    ColorValueVo( Color(0xFF79DEEC),) : "Spray",
    ColorValueVo( Color(0xFF7A013A),) : "Siren",
    ColorValueVo( Color(0xFF7A58C1),) : "Fuchsia Blue",
    ColorValueVo( Color(0xFF7A7A7A),) : "Boulder",
    ColorValueVo( Color(0xFF7A89B8),) : "Wild Blue Yonder",
    ColorValueVo( Color(0xFF7AC488),) : "De York",
    ColorValueVo( Color(0xFF7B3801),) : "Red Beech",
    ColorValueVo( Color(0xFF7B3F00),) : "Cinnamon",
    ColorValueVo( Color(0xFF7B6608),) : "Yukon Gold",
    ColorValueVo( Color(0xFF7B7874),) : "Tapa",
    ColorValueVo( Color(0xFF7B7C94),) : "Waterloo ",
    ColorValueVo( Color(0xFF7B8265),) : "Flax Smoke",
    ColorValueVo( Color(0xFF7B9F80),) : "Amulet",
    ColorValueVo( Color(0xFF7BA05B),) : "Asparagus",
    ColorValueVo( Color(0xFF7C1C05),) : "Kenyan Copper",
    ColorValueVo( Color(0xFF7C7631),) : "Pesto",
    ColorValueVo( Color(0xFF7C778A),) : "Topaz",
    ColorValueVo( Color(0xFF7C7B7A),) : "Concord",
    ColorValueVo( Color(0xFF7C7B82),) : "Jumbo",
    ColorValueVo( Color(0xFF7C881A),) : "Trendy Green",
    ColorValueVo( Color(0xFF7CA1A6),) : "Gumbo",
    ColorValueVo( Color(0xFF7CB0A1),) : "Acapulco",
    ColorValueVo( Color(0xFF7CB7BB),) : "Neptune",
    ColorValueVo( Color(0xFF7D2C14),) : "Pueblo",
    ColorValueVo( Color(0xFF7DA98D),) : "Bay Leaf",
    ColorValueVo( Color(0xFF7DC8F7),) : "Malibu",
    ColorValueVo( Color(0xFF7DD8C6),) : "Bermuda",
    ColorValueVo( Color(0xFF7E3A15),) : "Copper Canyon",
    ColorValueVo( Color(0xFF7F1734),) : "Claret",
    ColorValueVo( Color(0xFF7F3A02),) : "Peru Tan",
    ColorValueVo( Color(0xFF7F626D),) : "Falcon",
    ColorValueVo( Color(0xFF7F7589),) : "Mobster",
    ColorValueVo( Color(0xFF7F76D3),) : "Moody Blue",
    ColorValueVo( Color(0xFF7FFF00),) : "Chartreuse",
    ColorValueVo( Color(0xFF7FFFD4),) : "Aquamarine",
    ColorValueVo( Color(0xFF800000),) : "Maroon",
    ColorValueVo( Color(0xFF800B47),) : "Rose Bud Cherry",
    ColorValueVo( Color(0xFF801818),) : "Falu Red",
    ColorValueVo( Color(0xFF80341F),) : "Red Robin",
    ColorValueVo( Color(0xFF803790),) : "Vivid Violet",
    ColorValueVo( Color(0xFF80461B),) : "Russet",
    ColorValueVo( Color(0xFF807E79),) : "Friar Gray",
    ColorValueVo( Color(0xFF808000),) : "Olive",
    ColorValueVo( Color(0xFF808080),) : "Gray",
    ColorValueVo( Color(0xFF80B3AE),) : "Gulf Stream",
    ColorValueVo( Color(0xFF80B3C4),) : "Glacier",
    ColorValueVo( Color(0xFF80CCEA),) : "Seagull",
    ColorValueVo( Color(0xFF81422C),) : "Nutmeg",
    ColorValueVo( Color(0xFF816E71),) : "Spicy Pink",
    ColorValueVo( Color(0xFF817377),) : "Empress",
    ColorValueVo( Color(0xFF819885),) : "Spanish Green",
    ColorValueVo( Color(0xFF826F65),) : "Sand Dune",
    ColorValueVo( Color(0xFF828685),) : "Gunsmoke",
    ColorValueVo( Color(0xFF828F72),) : "Battleship Gray",
    ColorValueVo( Color(0xFF831923),) : "Merlot",
    ColorValueVo( Color(0xFF837050),) : "Shadow",
    ColorValueVo( Color(0xFF83AA5D),) : "Chelsea Cucumber",
    ColorValueVo( Color(0xFF83D0C6),) : "Monte Carlo",
    ColorValueVo( Color(0xFF843179),) : "Plum",
    ColorValueVo( Color(0xFF84A0A0),) : "Granny Smith",
    ColorValueVo( Color(0xFF8581D9),) : "Chetwode Blue",
    ColorValueVo( Color(0xFF858470),) : "Bandicoot",
    ColorValueVo( Color(0xFF859FAF),) : "Bali Hai",
    ColorValueVo( Color(0xFF85C4CC),) : "Half Baked",
    ColorValueVo( Color(0xFF860111),) : "Red Devil",
    ColorValueVo( Color(0xFF863C3C),) : "Lotus",
    ColorValueVo( Color(0xFF86483C),) : "Ironstone",
    ColorValueVo( Color(0xFF864D1E),) : "Bull Shot",
    ColorValueVo( Color(0xFF86560A),) : "Rusty Nail",
    ColorValueVo( Color(0xFF868974),) : "Bitter",
    ColorValueVo( Color(0xFF86949F),) : "Regent Gray",
    ColorValueVo( Color(0xFF871550),) : "Disco",
    ColorValueVo( Color(0xFF87756E),) : "Americano",
    ColorValueVo( Color(0xFF877C7B),) : "Hurricane",
    ColorValueVo( Color(0xFF878D91),) : "Oslo Gray",
    ColorValueVo( Color(0xFF87AB39),) : "Sushi",
    ColorValueVo( Color(0xFF885342),) : "Spicy Mix",
    ColorValueVo( Color(0xFF886221),) : "Kumera",
    ColorValueVo( Color(0xFF888387),) : "Suva Gray",
    ColorValueVo( Color(0xFF888D65),) : "Avocado",
    ColorValueVo( Color(0xFF893456),) : "Camelot",
    ColorValueVo( Color(0xFF893843),) : "Solid Pink",
    ColorValueVo( Color(0xFF894367),) : "Cannon Pink",
    ColorValueVo( Color(0xFF897D6D),) : "Makara",
    ColorValueVo( Color(0xFF8A3324),) : "Burnt Umber",
    ColorValueVo( Color(0xFF8A73D6),) : "True V",
    ColorValueVo( Color(0xFF8A8360),) : "Clay Creek",
    ColorValueVo( Color(0xFF8A8389),) : "Monsoon",
    ColorValueVo( Color(0xFF8A8F8A),) : "Stack",
    ColorValueVo( Color(0xFF8AB9F1),) : "Jordy Blue",
    ColorValueVo( Color(0xFF8B00FF),) : "Electric Violet",
    ColorValueVo( Color(0xFF8B0723),) : "Monarch",
    ColorValueVo( Color(0xFF8B6B0B),) : "Corn Harvest",
    ColorValueVo( Color(0xFF8B8470),) : "Olive Haze",
    ColorValueVo( Color(0xFF8B847E),) : "Schooner",
    ColorValueVo( Color(0xFF8B8680),) : "Natural Gray",
    ColorValueVo( Color(0xFF8B9C90),) : "Mantle",
    ColorValueVo( Color(0xFF8B9FEE),) : "Portage",
    ColorValueVo( Color(0xFF8BA690),) : "Envy",
    ColorValueVo( Color(0xFF8BA9A5),) : "Cascade",
    ColorValueVo( Color(0xFF8BE6D8),) : "Riptide",
    ColorValueVo( Color(0xFF8C055E),) : "Cardinal Pink",
    ColorValueVo( Color(0xFF8C472F),) : "Mule Fawn",
    ColorValueVo( Color(0xFF8C5738),) : "Potters Clay",
    ColorValueVo( Color(0xFF8C6495),) : "Trendy Pink",
    ColorValueVo( Color(0xFF8D0226),) : "Paprika",
    ColorValueVo( Color(0xFF8D3D38),) : "Sanguine Brown",
    ColorValueVo( Color(0xFF8D3F3F),) : "Tosca",
    ColorValueVo( Color(0xFF8D7662),) : "Cement",
    ColorValueVo( Color(0xFF8D8974),) : "Granite Green",
    ColorValueVo( Color(0xFF8D90A1),) : "Manatee",
    ColorValueVo( Color(0xFF8DA8CC),) : "Polo Blue",
    ColorValueVo( Color(0xFF8E0000),) : "Red Berry",
    ColorValueVo( Color(0xFF8E4D1E),) : "Rope",
    ColorValueVo( Color(0xFF8E6F70),) : "Opium",
    ColorValueVo( Color(0xFF8E775E),) : "Domino",
    ColorValueVo( Color(0xFF8E8190),) : "Mamba",
    ColorValueVo( Color(0xFF8EABC1),) : "Nepal",
    ColorValueVo( Color(0xFF8F021C),) : "Pohutukawa",
    ColorValueVo( Color(0xFF8F3E33),) : "El Salva",
    ColorValueVo( Color(0xFF8F4B0E),) : "Korma",
    ColorValueVo( Color(0xFF8F8176),) : "Squirrel",
    ColorValueVo( Color(0xFF8FD6B4),) : "Vista Blue",
    ColorValueVo( Color(0xFF900020),) : "Burgundy",
    ColorValueVo( Color(0xFF901E1E),) : "Old Brick",
    ColorValueVo( Color(0xFF907874),) : "Hemp",
    ColorValueVo( Color(0xFF907B71),) : "Almond Frost",
    ColorValueVo( Color(0xFF908D39),) : "Sycamore",
    ColorValueVo( Color(0xFF92000A),) : "Sangria",
    ColorValueVo( Color(0xFF924321),) : "Cumin",
    ColorValueVo( Color(0xFF926F5B),) : "Beaver",
    ColorValueVo( Color(0xFF928573),) : "Stonewall",
    ColorValueVo( Color(0xFF928590),) : "Venus",
    ColorValueVo( Color(0xFF9370DB),) : "Medium Purple",
    ColorValueVo( Color(0xFF93CCEA),) : "Cornflower",
    ColorValueVo( Color(0xFF93DFB8),) : "Algae Green",
    ColorValueVo( Color(0xFF944747),) : "Copper Rust",
    ColorValueVo( Color(0xFF948771),) : "Arrowtown",
    ColorValueVo( Color(0xFF950015),) : "Scarlett",
    ColorValueVo( Color(0xFF956387),) : "Strikemaster",
    ColorValueVo( Color(0xFF959396),) : "Mountain Mist",
    ColorValueVo( Color(0xFF960018),) : "Carmine",
    ColorValueVo( Color(0xFF964B00),) : "Brown",
    ColorValueVo( Color(0xFF967059),) : "Leather",
    ColorValueVo( Color(0xFF9678B6),) : "Purple Mountain's Majesty",
    ColorValueVo( Color(0xFF967BB6),) : "Lavender Purple",
    ColorValueVo( Color(0xFF96A8A1),) : "Pewter",
    ColorValueVo( Color(0xFF96BBAB),) : "Summer Green",
    ColorValueVo( Color(0xFF97605D),) : "Au Chico",
    ColorValueVo( Color(0xFF9771B5),) : "Wisteria",
    ColorValueVo( Color(0xFF97CD2D),) : "Atlantis",
    ColorValueVo( Color(0xFF983D61),) : "Vin Rouge",
    ColorValueVo( Color(0xFF9874D3),) : "Lilac Bush",
    ColorValueVo( Color(0xFF98777B),) : "Bazaar",
    ColorValueVo( Color(0xFF98811B),) : "Hacienda",
    ColorValueVo( Color(0xFF988D77),) : "Pale Oyster",
    ColorValueVo( Color(0xFF98FF98),) : "Mint Green",
    ColorValueVo( Color(0xFF990066),) : "Fresh Eggplant",
    ColorValueVo( Color(0xFF991199),) : "Violet Eggplant",
    ColorValueVo( Color(0xFF991613),) : "Tamarillo",
    ColorValueVo( Color(0xFF991B07),) : "Totem Pole",
    ColorValueVo( Color(0xFF996666),) : "Copper Rose",
    ColorValueVo( Color(0xFF9966CC),) : "Amethyst",
    ColorValueVo( Color(0xFF997A8D),) : "Mountbatten Pink",
    ColorValueVo( Color(0xFF9999CC),) : "Blue Bell",
    ColorValueVo( Color(0xFF9A3820),) : "Prairie Sand",
    ColorValueVo( Color(0xFF9A6E61),) : "Toast",
    ColorValueVo( Color(0xFF9A9577),) : "Gurkha",
    ColorValueVo( Color(0xFF9AB973),) : "Olivine",
    ColorValueVo( Color(0xFF9AC2B8),) : "Shadow Green",
    ColorValueVo( Color(0xFF9B4703),) : "Oregon",
    ColorValueVo( Color(0xFF9B9E8F),) : "Lemon Grass",
    ColorValueVo( Color(0xFF9C3336),) : "Stiletto",
    ColorValueVo( Color(0xFF9D5616),) : "Hawaiian Tan",
    ColorValueVo( Color(0xFF9DACB7),) : "Gull Gray",
    ColorValueVo( Color(0xFF9DC209),) : "Pistachio",
    ColorValueVo( Color(0xFF9DE093),) : "Granny Smith Apple",
    ColorValueVo( Color(0xFF9DE5FF),) : "Anakiwa",
    ColorValueVo( Color(0xFF9E5302),) : "Chelsea Gem",
    ColorValueVo( Color(0xFF9E5B40),) : "Sepia Skin",
    ColorValueVo( Color(0xFF9EA587),) : "Sage",
    ColorValueVo( Color(0xFF9EA91F),) : "Citron",
    ColorValueVo( Color(0xFF9EB1CD),) : "Rock Blue",
    ColorValueVo( Color(0xFF9EDEE0),) : "Morning Glory",
    ColorValueVo( Color(0xFF9F381D),) : "Cognac",
    ColorValueVo( Color(0xFF9F821C),) : "Reef Gold",
    ColorValueVo( Color(0xFF9F9F9C),) : "Star Dust",
    ColorValueVo( Color(0xFF9FA0B1),) : "Santas Gray",
    ColorValueVo( Color(0xFF9FD7D3),) : "Sinbad",
    ColorValueVo( Color(0xFF9FDD8C),) : "Feijoa",
    ColorValueVo( Color(0xFFA02712),) : "Tabasco",
    ColorValueVo( Color(0xFFA1750D),) : "Buttered Rum",
    ColorValueVo( Color(0xFFA1ADB5),) : "Hit Gray",
    ColorValueVo( Color(0xFFA1C50A),) : "Citrus",
    ColorValueVo( Color(0xFFA1DAD7),) : "Aqua Island",
    ColorValueVo( Color(0xFFA1E9DE),) : "Water Leaf",
    ColorValueVo( Color(0xFFA2006D),) : "Flirt",
    ColorValueVo( Color(0xFFA23B6C),) : "Rouge",
    ColorValueVo( Color(0xFFA26645),) : "Cape Palliser",
    ColorValueVo( Color(0xFFA2AAB3),) : "Gray Chateau",
    ColorValueVo( Color(0xFFA2AEAB),) : "Edward",
    ColorValueVo( Color(0xFFA3807B),) : "Pharlap",
    ColorValueVo( Color(0xFFA397B4),) : "Amethyst Smoke",
    ColorValueVo( Color(0xFFA3E3ED),) : "Blizzard Blue",
    ColorValueVo( Color(0xFFA4A49D),) : "Delta",
    ColorValueVo( Color(0xFFA4A6D3),) : "Wistful",
    ColorValueVo( Color(0xFFA4AF6E),) : "Green Smoke",
    ColorValueVo( Color(0xFFA50B5E),) : "Jazzberry Jam",
    ColorValueVo( Color(0xFFA59B91),) : "Zorba",
    ColorValueVo( Color(0xFFA5CB0C),) : "Bahia",
    ColorValueVo( Color(0xFFA62F20),) : "Roof Terracotta",
    ColorValueVo( Color(0xFFA65529),) : "Paarl",
    ColorValueVo( Color(0xFFA68B5B),) : "Barley Corn",
    ColorValueVo( Color(0xFFA69279),) : "Donkey Brown",
    ColorValueVo( Color(0xFFA6A29A),) : "Dawn",
    ColorValueVo( Color(0xFFA72525),) : "Mexican Red",
    ColorValueVo( Color(0xFFA7882C),) : "Luxor Gold",
    ColorValueVo( Color(0xFFA85307),) : "Rich Gold",
    ColorValueVo( Color(0xFFA86515),) : "Reno Sand",
    ColorValueVo( Color(0xFFA86B6B),) : "Coral Tree",
    ColorValueVo( Color(0xFFA8989B),) : "Dusty Gray",
    ColorValueVo( Color(0xFFA899E6),) : "Dull Lavender",
    ColorValueVo( Color(0xFFA8A589),) : "Tallow",
    ColorValueVo( Color(0xFFA8AE9C),) : "Bud",
    ColorValueVo( Color(0xFFA8AF8E),) : "Locust",
    ColorValueVo( Color(0xFFA8BD9F),) : "Norway",
    ColorValueVo( Color(0xFFA8E3BD),) : "Chinook",
    ColorValueVo( Color(0xFFA9A491),) : "Gray Olive",
    ColorValueVo( Color(0xFFA9ACB6),) : "Aluminium",
    ColorValueVo( Color(0xFFA9B2C3),) : "Cadet Blue",
    ColorValueVo( Color(0xFFA9B497),) : "Schist",
    ColorValueVo( Color(0xFFA9BDBF),) : "Tower Gray",
    ColorValueVo( Color(0xFFA9BEF2),) : "Perano",
    ColorValueVo( Color(0xFFA9C6C2),) : "Opal",
    ColorValueVo( Color(0xFFAA375A),) : "Night Shadz",
    ColorValueVo( Color(0xFFAA4203),) : "Fire",
    ColorValueVo( Color(0xFFAA8B5B),) : "Muesli",
    ColorValueVo( Color(0xFFAA8D6F),) : "Sandal",
    ColorValueVo( Color(0xFFAAA5A9),) : "Shady Lady",
    ColorValueVo( Color(0xFFAAA9CD),) : "Logan",
    ColorValueVo( Color(0xFFAAABB7),) : "Spun Pearl",
    ColorValueVo( Color(0xFFAAD6E6),) : "Regent St Blue",
    ColorValueVo( Color(0xFFAAF0D1),) : "Magic Mint",
    ColorValueVo( Color(0xFFAB0563),) : "Lipstick",
    ColorValueVo( Color(0xFFAB3472),) : "Royal Heath",
    ColorValueVo( Color(0xFFAB917A),) : "Sandrift",
    ColorValueVo( Color(0xFFABA0D9),) : "Cold Purple",
    ColorValueVo( Color(0xFFABA196),) : "Bronco",
    ColorValueVo( Color(0xFFAC8A56),) : "Limed Oak",
    ColorValueVo( Color(0xFFAC91CE),) : "East Side",
    ColorValueVo( Color(0xFFAC9E22),) : "Lemon Ginger",
    ColorValueVo( Color(0xFFACA494),) : "Napa",
    ColorValueVo( Color(0xFFACA586),) : "Hillary",
    ColorValueVo( Color(0xFFACA59F),) : "Cloudy",
    ColorValueVo( Color(0xFFACACAC),) : "Silver Chalice",
    ColorValueVo( Color(0xFFACB78E),) : "Swamp Green",
    ColorValueVo( Color(0xFFACCBB1),) : "Spring Rain",
    ColorValueVo( Color(0xFFACDD4D),) : "Conifer",
    ColorValueVo( Color(0xFFACE1AF),) : "Celadon",
    ColorValueVo( Color(0xFFAD781B),) : "Mandalay",
    ColorValueVo( Color(0xFFADBED1),) : "Casper",
    ColorValueVo( Color(0xFFADDFAD),) : "Moss Green",
    ColorValueVo( Color(0xFFADE6C4),) : "Padua",
    ColorValueVo( Color(0xFFADFF2F),) : "Green Yellow",
    ColorValueVo( Color(0xFFAE4560),) : "Hippie Pink",
    ColorValueVo( Color(0xFFAE6020),) : "Desert",
    ColorValueVo( Color(0xFFAE809E),) : "Bouquet",
    ColorValueVo( Color(0xFFAF4035),) : "Medium Carmine",
    ColorValueVo( Color(0xFFAF4D43),) : "Apple Blossom",
    ColorValueVo( Color(0xFFAF593E),) : "Brown Rust",
    ColorValueVo( Color(0xFFAF8751),) : "Driftwood",
    ColorValueVo( Color(0xFFAF8F2C),) : "Alpine",
    ColorValueVo( Color(0xFFAF9F1C),) : "Lucky",
    ColorValueVo( Color(0xFFAFA09E),) : "Martini",
    ColorValueVo( Color(0xFFAFB1B8),) : "Bombay",
    ColorValueVo( Color(0xFFAFBDD9),) : "Pigeon Post",
    ColorValueVo( Color(0xFFB04C6A),) : "Cadillac",
    ColorValueVo( Color(0xFFB05D54),) : "Matrix",
    ColorValueVo( Color(0xFFB05E81),) : "Tapestry",
    ColorValueVo( Color(0xFFB06608),) : "Mai Tai",
    ColorValueVo( Color(0xFFB09A95),) : "Del Rio",
    ColorValueVo( Color(0xFFB0E0E6),) : "Powder Blue",
    ColorValueVo( Color(0xFFB0E313),) : "Inch Worm",
    ColorValueVo( Color(0xFFB10000),) : "Bright Red",
    ColorValueVo( Color(0xFFB14A0B),) : "Vesuvius",
    ColorValueVo( Color(0xFFB1610B),) : "Pumpkin Skin",
    ColorValueVo( Color(0xFFB16D52),) : "Santa Fe",
    ColorValueVo( Color(0xFFB19461),) : "Teak",
    ColorValueVo( Color(0xFFB1E2C1),) : "Fringy Flower",
    ColorValueVo( Color(0xFFB1F4E7),) : "Ice Cold",
    ColorValueVo( Color(0xFFB20931),) : "Shiraz",
    ColorValueVo( Color(0xFFB2A1EA),) : "Biloba Flower",
    ColorValueVo( Color(0xFFB32D29),) : "Tall Poppy",
    ColorValueVo( Color(0xFFB35213),) : "Fiery Orange",
    ColorValueVo( Color(0xFFB38007),) : "Hot Toddy",
    ColorValueVo( Color(0xFFB3AF95),) : "Taupe Gray",
    ColorValueVo( Color(0xFFB3C110),) : "La Rioja",
    ColorValueVo( Color(0xFFB43332),) : "Well Read",
    ColorValueVo( Color(0xFFB44668),) : "Blush",
    ColorValueVo( Color(0xFFB4CFD3),) : "Jungle Mist",
    ColorValueVo( Color(0xFFB57281),) : "Turkish Rose",
    ColorValueVo( Color(0xFFB57EDC),) : "Lavender",
    ColorValueVo( Color(0xFFB5A27F),) : "Mongoose",
    ColorValueVo( Color(0xFFB5B35C),) : "Olive Green",
    ColorValueVo( Color(0xFFB5D2CE),) : "Jet Stream",
    ColorValueVo( Color(0xFFB5ECDF),) : "Cruise",
    ColorValueVo( Color(0xFFB6316C),) : "Hibiscus",
    ColorValueVo( Color(0xFFB69D98),) : "Thatch",
    ColorValueVo( Color(0xFFB6B095),) : "Heathered Gray",
    ColorValueVo( Color(0xFFB6BAA4),) : "Eagle",
    ColorValueVo( Color(0xFFB6D1EA),) : "Spindle",
    ColorValueVo( Color(0xFFB6D3BF),) : "Gum Leaf",
    ColorValueVo( Color(0xFFB7410E),) : "Rust",
    ColorValueVo( Color(0xFFB78E5C),) : "Muddy Waters",
    ColorValueVo( Color(0xFFB7A214),) : "Sahara",
    ColorValueVo( Color(0xFFB7A458),) : "Husk",
    ColorValueVo( Color(0xFFB7B1B1),) : "Nobel",
    ColorValueVo( Color(0xFFB7C3D0),) : "Heather",
    ColorValueVo( Color(0xFFB7F0BE),) : "Madang",
    ColorValueVo( Color(0xFFB81104),) : "Milano Red",
    ColorValueVo( Color(0xFFB87333),) : "Copper",
    ColorValueVo( Color(0xFFB8B56A),) : "Gimblet",
    ColorValueVo( Color(0xFFB8C1B1),) : "Green Spring",
    ColorValueVo( Color(0xFFB8C25D),) : "Celery",
    ColorValueVo( Color(0xFFB8E0F9),) : "Sail",
    ColorValueVo( Color(0xFFB94E48),) : "Chestnut",
    ColorValueVo( Color(0xFFB95140),) : "Crail",
    ColorValueVo( Color(0xFFB98D28),) : "Marigold",
    ColorValueVo( Color(0xFFB9C46A),) : "Wild Willow",
    ColorValueVo( Color(0xFFB9C8AC),) : "Rainee",
    ColorValueVo( Color(0xFFBA0101),) : "Guardsman Red",
    ColorValueVo( Color(0xFFBA450C),) : "Rock Spray",
    ColorValueVo( Color(0xFFBA6F1E),) : "Bourbon",
    ColorValueVo( Color(0xFFBA7F03),) : "Pirate Gold",
    ColorValueVo( Color(0xFFBAB1A2),) : "Nomad",
    ColorValueVo( Color(0xFFBAC7C9),) : "Submarine",
    ColorValueVo( Color(0xFFBAEEF9),) : "Charlotte",
    ColorValueVo( Color(0xFFBB3385),) : "Medium Red Violet",
    ColorValueVo( Color(0xFFBB8983),) : "Brandy Rose",
    ColorValueVo( Color(0xFFBBD009),) : "Rio Grande",
    ColorValueVo( Color(0xFFBBD7C1),) : "Surf",
    ColorValueVo( Color(0xFFBCC9C2),) : "Powder Ash",
    ColorValueVo( Color(0xFFBD5E2E),) : "Tuscany",
    ColorValueVo( Color(0xFFBD978E),) : "Quicksand",
    ColorValueVo( Color(0xFFBDB1A8),) : "Silk",
    ColorValueVo( Color(0xFFBDB2A1),) : "Malta",
    ColorValueVo( Color(0xFFBDB3C7),) : "Chatelle",
    ColorValueVo( Color(0xFFBDBBD7),) : "Lavender Gray",
    ColorValueVo( Color(0xFFBDBDC6),) : "French Gray",
    ColorValueVo( Color(0xFFBDC8B3),) : "Clay Ash",
    ColorValueVo( Color(0xFFBDC9CE),) : "Loblolly",
    ColorValueVo( Color(0xFFBDEDFD),) : "French Pass",
    ColorValueVo( Color(0xFFBEA6C3),) : "London Hue",
    ColorValueVo( Color(0xFFBEB5B7),) : "Pink Swan",
    ColorValueVo( Color(0xFFBEDE0D),) : "Fuego",
    ColorValueVo( Color(0xFFBF5500),) : "Rose of Sharon",
    ColorValueVo( Color(0xFFBFB8B0),) : "Tide",
    ColorValueVo( Color(0xFFBFBED8),) : "Blue Haze",
    ColorValueVo( Color(0xFFBFC1C2),) : "Silver Sand",
    ColorValueVo( Color(0xFFBFC921),) : "Key Lime Pie",
    ColorValueVo( Color(0xFFBFDBE2),) : "Ziggurat",
    ColorValueVo( Color(0xFFBFFF00),) : "Lime",
    ColorValueVo( Color(0xFFC02B18),) : "Thunderbird",
    ColorValueVo( Color(0xFFC04737),) : "Mojo",
    ColorValueVo( Color(0xFFC08081),) : "Old Rose",
    ColorValueVo( Color(0xFFC0C0C0),) : "Silver",
    ColorValueVo( Color(0xFFC0D3B9),) : "Pale Leaf",
    ColorValueVo( Color(0xFFC0D8B6),) : "Pixie Green",
    ColorValueVo( Color(0xFFC1440E),) : "Tia Maria",
    ColorValueVo( Color(0xFFC154C1),) : "Fuchsia Pink",
    ColorValueVo( Color(0xFFC1A004),) : "Buddha Gold",
    ColorValueVo( Color(0xFFC1B7A4),) : "Bison Hide",
    ColorValueVo( Color(0xFFC1BAB0),) : "Tea",
    ColorValueVo( Color(0xFFC1BECD),) : "Gray Suit",
    ColorValueVo( Color(0xFFC1D7B0),) : "Sprout",
    ColorValueVo( Color(0xFFC1F07C),) : "Sulu",
    ColorValueVo( Color(0xFFC26B03),) : "Indochine",
    ColorValueVo( Color(0xFFC2955D),) : "Twine",
    ColorValueVo( Color(0xFFC2BDB6),) : "Cotton Seed",
    ColorValueVo( Color(0xFFC2CAC4),) : "Pumice",
    ColorValueVo( Color(0xFFC2E8E5),) : "Jagged Ice",
    ColorValueVo( Color(0xFFC32148),) : "Maroon Flush",
    ColorValueVo( Color(0xFFC3B091),) : "Indian Khaki",
    ColorValueVo( Color(0xFFC3BFC1),) : "Pale Slate",
    ColorValueVo( Color(0xFFC3C3BD),) : "Gray Nickel",
    ColorValueVo( Color(0xFFC3CDE6),) : "Periwinkle Gray",
    ColorValueVo( Color(0xFFC3D1D1),) : "Tiara",
    ColorValueVo( Color(0xFFC3DDF9),) : "Tropical Blue",
    ColorValueVo( Color(0xFFC41E3A),) : "Cardinal",
    ColorValueVo( Color(0xFFC45655),) : "Fuzzy Wuzzy Brown",
    ColorValueVo( Color(0xFFC45719),) : "Orange Roughy",
    ColorValueVo( Color(0xFFC4C4BC),) : "Mist Gray",
    ColorValueVo( Color(0xFFC4D0B0),) : "Coriander",
    ColorValueVo( Color(0xFFC4F4EB),) : "Mint Tulip",
    ColorValueVo( Color(0xFFC54B8C),) : "Mulberry",
    ColorValueVo( Color(0xFFC59922),) : "Nugget",
    ColorValueVo( Color(0xFFC5994B),) : "Tussock",
    ColorValueVo( Color(0xFFC5DBCA),) : "Sea Mist",
    ColorValueVo( Color(0xFFC5E17A),) : "Yellow Green",
    ColorValueVo( Color(0xFFC62D42),) : "Brick Red",
    ColorValueVo( Color(0xFFC6726B),) : "Contessa",
    ColorValueVo( Color(0xFFC69191),) : "Oriental Pink",
    ColorValueVo( Color(0xFFC6A84B),) : "Roti",
    ColorValueVo( Color(0xFFC6C3B5),) : "Ash",
    ColorValueVo( Color(0xFFC6C8BD),) : "Kangaroo",
    ColorValueVo( Color(0xFFC6E610),) : "Las Palmas",
    ColorValueVo( Color(0xFFC7031E),) : "Monza",
    ColorValueVo( Color(0xFFC71585),) : "Red Violet",
    ColorValueVo( Color(0xFFC7BCA2),) : "Coral Reef",
    ColorValueVo( Color(0xFFC7C1FF),) : "Melrose",
    ColorValueVo( Color(0xFFC7C4BF),) : "Cloud",
    ColorValueVo( Color(0xFFC7C9D5),) : "Ghost",
    ColorValueVo( Color(0xFFC7CD90),) : "Pine Glade",
    ColorValueVo( Color(0xFFC7DDE5),) : "Botticelli",
    ColorValueVo( Color(0xFFC88A65),) : "Antique Brass",
    ColorValueVo( Color(0xFFC8A2C8),) : "Lilac",
    ColorValueVo( Color(0xFFC8A528),) : "Hokey Pokey",
    ColorValueVo( Color(0xFFC8AABF),) : "Lily",
    ColorValueVo( Color(0xFFC8B568),) : "Laser",
    ColorValueVo( Color(0xFFC8E3D7),) : "Edgewater",
    ColorValueVo( Color(0xFFC96323),) : "Piper",
    ColorValueVo( Color(0xFFC99415),) : "Pizza",
    ColorValueVo( Color(0xFFC9A0DC),) : "Light Wisteria",
    ColorValueVo( Color(0xFFC9B29B),) : "Rodeo Dust",
    ColorValueVo( Color(0xFFC9B35B),) : "Sundance",
    ColorValueVo( Color(0xFFC9B93B),) : "Earls Green",
    ColorValueVo( Color(0xFFC9C0BB),) : "Silver Rust",
    ColorValueVo( Color(0xFFC9D9D2),) : "Conch",
    ColorValueVo( Color(0xFFC9FFA2),) : "Reef",
    ColorValueVo( Color(0xFFC9FFE5),) : "Aero Blue",
    ColorValueVo( Color(0xFFCA3435),) : "Flush Mahogany",
    ColorValueVo( Color(0xFFCABB48),) : "Turmeric",
    ColorValueVo( Color(0xFFCADCD4),) : "Paris White",
    ColorValueVo( Color(0xFFCAE00D),) : "Bitter Lemon",
    ColorValueVo( Color(0xFFCAE6DA),) : "Skeptic",
    ColorValueVo( Color(0xFFCB8FA9),) : "Viola",
    ColorValueVo( Color(0xFFCBCAB6),) : "Foggy Gray",
    ColorValueVo( Color(0xFFCBD3B0),) : "Green Mist",
    ColorValueVo( Color(0xFFCBDBD6),) : "Nebula",
    ColorValueVo( Color(0xFFCC3333),) : "Persian Red",
    ColorValueVo( Color(0xFFCC5500),) : "Burnt Orange",
    ColorValueVo( Color(0xFFCC7722),) : "Ochre",
    ColorValueVo( Color(0xFFCC8899),) : "Puce",
    ColorValueVo( Color(0xFFCCCAA8),) : "Thistle Green",
    ColorValueVo( Color(0xFFCCCCFF),) : "Periwinkle",
    ColorValueVo( Color(0xFFCCFF00),) : "Electric Lime",
    ColorValueVo( Color(0xFFCD5700),) : "Tenn",
    ColorValueVo( Color(0xFFCD5C5C),) : "Chestnut Rose",
    ColorValueVo( Color(0xFFCD8429),) : "Brandy Punch",
    ColorValueVo( Color(0xFFCDF4FF),) : "Onahau",
    ColorValueVo( Color(0xFFCEB98F),) : "Sorrell Brown",
    ColorValueVo( Color(0xFFCEBABA),) : "Cold Turkey",
    ColorValueVo( Color(0xFFCEC291),) : "Yuma",
    ColorValueVo( Color(0xFFCEC7A7),) : "Chino",
    ColorValueVo( Color(0xFFCFA39D),) : "Eunry",
    ColorValueVo( Color(0xFFCFB53B),) : "Old Gold",
    ColorValueVo( Color(0xFFCFDCCF),) : "Tasman",
    ColorValueVo( Color(0xFFCFE5D2),) : "Surf Crest",
    ColorValueVo( Color(0xFFCFF9F3),) : "Humming Bird",
    ColorValueVo( Color(0xFFCFFAF4),) : "Scandal",
    ColorValueVo( Color(0xFFD05F04),) : "Red Stage",
    ColorValueVo( Color(0xFFD06DA1),) : "Hopbush",
    ColorValueVo( Color(0xFFD07D12),) : "Meteor",
    ColorValueVo( Color(0xFFD0BEF8),) : "Perfume",
    ColorValueVo( Color(0xFFD0C0E5),) : "Prelude",
    ColorValueVo( Color(0xFFD0F0C0),) : "Tea Green",
    ColorValueVo( Color(0xFFD18F1B),) : "Geebung",
    ColorValueVo( Color(0xFFD1BEA8),) : "Vanilla",
    ColorValueVo( Color(0xFFD1C6B4),) : "Soft Amber",
    ColorValueVo( Color(0xFFD1D2CA),) : "Celeste",
    ColorValueVo( Color(0xFFD1D2DD),) : "Mischka",
    ColorValueVo( Color(0xFFD1E231),) : "Pear",
    ColorValueVo( Color(0xFFD2691E),) : "Hot Cinnamon",
    ColorValueVo( Color(0xFFD27D46),) : "Raw Sienna",
    ColorValueVo( Color(0xFFD29EAA),) : "Careys Pink",
    ColorValueVo( Color(0xFFD2B48C),) : "Tan",
    ColorValueVo( Color(0xFFD2DA97),) : "Deco",
    ColorValueVo( Color(0xFFD2F6DE),) : "Blue Romance",
    ColorValueVo( Color(0xFFD2F8B0),) : "Gossip",
    ColorValueVo( Color(0xFFD3CBBA),) : "Sisal",
    ColorValueVo( Color(0xFFD3CDC5),) : "Swirl",
    ColorValueVo( Color(0xFFD47494),) : "Charm",
    ColorValueVo( Color(0xFFD4B6AF),) : "Clam Shell",
    ColorValueVo( Color(0xFFD4BF8D),) : "Straw",
    ColorValueVo( Color(0xFFD4C4A8),) : "Akaroa",
    ColorValueVo( Color(0xFFD4CD16),) : "Bird Flower",
    ColorValueVo( Color(0xFFD4D7D9),) : "Iron",
    ColorValueVo( Color(0xFFD4DFE2),) : "Geyser",
    ColorValueVo( Color(0xFFD4E2FC),) : "Hawkes Blue",
    ColorValueVo( Color(0xFFD54600),) : "Grenadier",
    ColorValueVo( Color(0xFFD591A4),) : "Can Can",
    ColorValueVo( Color(0xFFD59A6F),) : "Whiskey",
    ColorValueVo( Color(0xFFD5D195),) : "Winter Hazel",
    ColorValueVo( Color(0xFFD5F6E3),) : "Granny Apple",
    ColorValueVo( Color(0xFFD69188),) : "My Pink",
    ColorValueVo( Color(0xFFD6C562),) : "Tacha",
    ColorValueVo( Color(0xFFD6CEF6),) : "Moon Raker",
    ColorValueVo( Color(0xFFD6D6D1),) : "Quill Gray",
    ColorValueVo( Color(0xFFD6FFDB),) : "Snowy Mint",
    ColorValueVo( Color(0xFFD7837F),) : "New York Pink",
    ColorValueVo( Color(0xFFD7C498),) : "Pavlova",
    ColorValueVo( Color(0xFFD7D0FF),) : "Fog",
    ColorValueVo( Color(0xFFD84437),) : "Valencia",
    ColorValueVo( Color(0xFFD87C63),) : "Japonica",
    ColorValueVo( Color(0xFFD8BFD8),) : "Thistle",
    ColorValueVo( Color(0xFFD8C2D5),) : "Maverick",
    ColorValueVo( Color(0xFFD8FCFA),) : "Foam",
    ColorValueVo( Color(0xFFD94972),) : "Cabaret",
    ColorValueVo( Color(0xFFD99376),) : "Burning Sand",
    ColorValueVo( Color(0xFFD9B99B),) : "Cameo",
    ColorValueVo( Color(0xFFD9D6CF),) : "Timberwolf",
    ColorValueVo( Color(0xFFD9DCC1),) : "Tana",
    ColorValueVo( Color(0xFFD9E4F5),) : "Link Water",
    ColorValueVo( Color(0xFFD9F7FF),) : "Mabel",
    ColorValueVo( Color(0xFFDA3287),) : "Cerise",
    ColorValueVo( Color(0xFFDA5B38),) : "Flame Pea",
    ColorValueVo( Color(0xFFDA6304),) : "Bamboo",
    ColorValueVo( Color(0xFFDA6A41),) : "Red Damask",
    ColorValueVo( Color(0xFFDA70D6),) : "Orchid",
    ColorValueVo( Color(0xFFDA8A67),) : "Copperfield",
    ColorValueVo( Color(0xFFDAA520),) : "Golden Grass",
    ColorValueVo( Color(0xFFDAECD6),) : "Zanah",
    ColorValueVo( Color(0xFFDAF4F0),) : "Iceberg",
    ColorValueVo( Color(0xFFDAFAFF),) : "Oyster Bay",
    ColorValueVo( Color(0xFFDB5079),) : "Cranberry",
    ColorValueVo( Color(0xFFDB9690),) : "Petite Orchid",
    ColorValueVo( Color(0xFFDB995E),) : "Di Serria",
    ColorValueVo( Color(0xFFDBDBDB),) : "Alto",
    ColorValueVo( Color(0xFFDBFFF8),) : "Frosted Mint",
    ColorValueVo( Color(0xFFDC143C),) : "Crimson",
    ColorValueVo( Color(0xFFDC4333),) : "Punch",
    ColorValueVo( Color(0xFFDCB20C),) : "Galliano",
    ColorValueVo( Color(0xFFDCB4BC),) : "Blossom",
    ColorValueVo( Color(0xFFDCD747),) : "Wattle",
    ColorValueVo( Color(0xFFDCD9D2),) : "Westar",
    ColorValueVo( Color(0xFFDCDDCC),) : "Moon Mist",
    ColorValueVo( Color(0xFFDCEDB4),) : "Caper",
    ColorValueVo( Color(0xFFDCF0EA),) : "Swans Down",
    ColorValueVo( Color(0xFFDDD6D5),) : "Swiss Coffee",
    ColorValueVo( Color(0xFFDDF9F1),) : "White Ice",
    ColorValueVo( Color(0xFFDE3163),) : "Cerise Red",
    ColorValueVo( Color(0xFFDE6360),) : "Roman",
    ColorValueVo( Color(0xFFDEA681),) : "Tumbleweed",
    ColorValueVo( Color(0xFFDEBA13),) : "Gold Tips",
    ColorValueVo( Color(0xFFDEC196),) : "Brandy",
    ColorValueVo( Color(0xFFDECBC6),) : "Wafer",
    ColorValueVo( Color(0xFFDED4A4),) : "Sapling",
    ColorValueVo( Color(0xFFDED717),) : "Barberry",
    ColorValueVo( Color(0xFFDEE5C0),) : "Beryl Green",
    ColorValueVo( Color(0xFFDEF5FF),) : "Pattens Blue",
    ColorValueVo( Color(0xFFDF73FF),) : "Heliotrope",
    ColorValueVo( Color(0xFFDFBE6F),) : "Apache",
    ColorValueVo( Color(0xFFDFCD6F),) : "Chenin",
    ColorValueVo( Color(0xFFDFCFDB),) : "Lola",
    ColorValueVo( Color(0xFFDFECDA),) : "Willow Brook",
    ColorValueVo( Color(0xFFDFFF00),) : "Chartreuse Yellow",
    ColorValueVo( Color(0xFFE0B0FF),) : "Mauve",
    ColorValueVo( Color(0xFFE0B646),) : "Anzac",
    ColorValueVo( Color(0xFFE0B974),) : "Harvest Gold",
    ColorValueVo( Color(0xFFE0C095),) : "Calico",
    ColorValueVo( Color(0xFFE0FFFF),) : "Baby Blue",
    ColorValueVo( Color(0xFFE16865),) : "Sunglo",
    ColorValueVo( Color(0xFFE1BC64),) : "Equator",
    ColorValueVo( Color(0xFFE1C0C8),) : "Pink Flare",
    ColorValueVo( Color(0xFFE1E6D6),) : "Periglacial Blue",
    ColorValueVo( Color(0xFFE1EAD4),) : "Kidnapper",
    ColorValueVo( Color(0xFFE1F6E8),) : "Tara",
    ColorValueVo( Color(0xFFE25465),) : "Mandy",
    ColorValueVo( Color(0xFFE2725B),) : "Terracotta",
    ColorValueVo( Color(0xFFE28913),) : "Golden Bell",
    ColorValueVo( Color(0xFFE292C0),) : "Shocking",
    ColorValueVo( Color(0xFFE29418),) : "Dixie",
    ColorValueVo( Color(0xFFE29CD2),) : "Light Orchid",
    ColorValueVo( Color(0xFFE2D8ED),) : "Snuff",
    ColorValueVo( Color(0xFFE2EBED),) : "Mystic",
    ColorValueVo( Color(0xFFE2F3EC),) : "Apple Green",
    ColorValueVo( Color(0xFFE30B5C),) : "Razzmatazz",
    ColorValueVo( Color(0xFFE32636),) : "Alizarin Crimson",
    ColorValueVo( Color(0xFFE34234),) : "Cinnabar",
    ColorValueVo( Color(0xFFE3BEBE),) : "Cavern Pink",
    ColorValueVo( Color(0xFFE3F5E1),) : "Peppermint",
    ColorValueVo( Color(0xFFE3F988),) : "Mindaro",
    ColorValueVo( Color(0xFFE47698),) : "Deep Blush",
    ColorValueVo( Color(0xFFE49B0F),) : "Gamboge",
    ColorValueVo( Color(0xFFE4C2D5),) : "Melanie",
    ColorValueVo( Color(0xFFE4CFDE),) : "Twilight",
    ColorValueVo( Color(0xFFE4D1C0),) : "Bone",
    ColorValueVo( Color(0xFFE4D422),) : "Sunflower",
    ColorValueVo( Color(0xFFE4D5B7),) : "Grain Brown",
    ColorValueVo( Color(0xFFE4D69B),) : "Zombie",
    ColorValueVo( Color(0xFFE4F6E7),) : "Frostee",
    ColorValueVo( Color(0xFFE4FFD1),) : "Snow Flurry",
    ColorValueVo( Color(0xFFE52B50),) : "Amaranth",
    ColorValueVo( Color(0xFFE5841B),) : "Zest",
    ColorValueVo( Color(0xFFE5CCC9),) : "Dust Storm",
    ColorValueVo( Color(0xFFE5D7BD),) : "Stark White",
    ColorValueVo( Color(0xFFE5D8AF),) : "Hampton",
    ColorValueVo( Color(0xFFE5E0E1),) : "Bon Jour",
    ColorValueVo( Color(0xFFE5E5E5),) : "Mercury",
    ColorValueVo( Color(0xFFE5F9F6),) : "Polar",
    ColorValueVo( Color(0xFFE64E03),) : "Trinidad",
    ColorValueVo( Color(0xFFE6BE8A),) : "Gold Sand",
    ColorValueVo( Color(0xFFE6BEA5),) : "Cashmere",
    ColorValueVo( Color(0xFFE6D7B9),) : "Double Spanish White",
    ColorValueVo( Color(0xFFE6E4D4),) : "Satin Linen",
    ColorValueVo( Color(0xFFE6F2EA),) : "Harp",
    ColorValueVo( Color(0xFFE6F8F3),) : "Off Green",
    ColorValueVo( Color(0xFFE6FFE9),) : "Hint of Green",
    ColorValueVo( Color(0xFFE6FFFF),) : "Tranquil",
    ColorValueVo( Color(0xFFE77200),) : "Mango Tango",
    ColorValueVo( Color(0xFFE7730A),) : "Christine",
    ColorValueVo( Color(0xFFE79F8C),) : "Tonys Pink",
    ColorValueVo( Color(0xFFE79FC4),) : "Kobi",
    ColorValueVo( Color(0xFFE7BCB4),) : "Rose Fog",
    ColorValueVo( Color(0xFFE7BF05),) : "Corn",
    ColorValueVo( Color(0xFFE7CD8C),) : "Putty",
    ColorValueVo( Color(0xFFE7ECE6),) : "Gray Nurse",
    ColorValueVo( Color(0xFFE7F8FF),) : "Lily White",
    ColorValueVo( Color(0xFFE7FEFF),) : "Bubbles",
    ColorValueVo( Color(0xFFE89928),) : "Fire Bush",
    ColorValueVo( Color(0xFFE8B9B3),) : "Shilo",
    ColorValueVo( Color(0xFFE8E0D5),) : "Pearl Bush",
    ColorValueVo( Color(0xFFE8EBE0),) : "Green White",
    ColorValueVo( Color(0xFFE8F1D4),) : "Chrome White",
    ColorValueVo( Color(0xFFE8F2EB),) : "Gin",
    ColorValueVo( Color(0xFFE8F5F2),) : "Aqua Squeeze",
    ColorValueVo( Color(0xFFE96E00),) : "Clementine",
    ColorValueVo( Color(0xFFE97451),) : "Burnt Sienna",
    ColorValueVo( Color(0xFFE97C07),) : "Tahiti Gold",
    ColorValueVo( Color(0xFFE9CECD),) : "Oyster Pink",
    ColorValueVo( Color(0xFFE9D75A),) : "Confetti",
    ColorValueVo( Color(0xFFE9E3E3),) : "Ebb",
    ColorValueVo( Color(0xFFE9F8ED),) : "Ottoman",
    ColorValueVo( Color(0xFFE9FFFD),) : "Clear Day",
    ColorValueVo( Color(0xFFEA88A8),) : "Carissma",
    ColorValueVo( Color(0xFFEAAE69),) : "Porsche",
    ColorValueVo( Color(0xFFEAB33B),) : "Tulip Tree",
    ColorValueVo( Color(0xFFEAC674),) : "Rob Roy",
    ColorValueVo( Color(0xFFEADAB8),) : "Raffia",
    ColorValueVo( Color(0xFFEAE8D4),) : "White Rock",
    ColorValueVo( Color(0xFFEAF6EE),) : "Panache",
    ColorValueVo( Color(0xFFEAF6FF),) : "Solitude",
    ColorValueVo( Color(0xFFEAF9F5),) : "Aqua Spring",
    ColorValueVo( Color(0xFFEAFFFE),) : "Dew",
    ColorValueVo( Color(0xFFEB9373),) : "Apricot",
    ColorValueVo( Color(0xFFEBC2AF),) : "Zinnwaldite",
    ColorValueVo( Color(0xFFECA927),) : "Fuel Yellow",
    ColorValueVo( Color(0xFFECC54E),) : "Ronchi",
    ColorValueVo( Color(0xFFECC7EE),) : "French Lilac",
    ColorValueVo( Color(0xFFECCDB9),) : "Just Right",
    ColorValueVo( Color(0xFFECE090),) : "Wild Rice",
    ColorValueVo( Color(0xFFECEBBD),) : "Fall Green",
    ColorValueVo( Color(0xFFECEBCE),) : "Aths Special",
    ColorValueVo( Color(0xFFECF245),) : "Starship",
    ColorValueVo( Color(0xFFED0A3F),) : "Red Ribbon",
    ColorValueVo( Color(0xFFED7A1C),) : "Tango",
    ColorValueVo( Color(0xFFED9121),) : "Carrot Orange",
    ColorValueVo( Color(0xFFED989E),) : "Sea Pink",
    ColorValueVo( Color(0xFFEDB381),) : "Tacao",
    ColorValueVo( Color(0xFFEDC9AF),) : "Desert Sand",
    ColorValueVo( Color(0xFFEDCDAB),) : "Pancho",
    ColorValueVo( Color(0xFFEDDCB1),) : "Chamois",
    ColorValueVo( Color(0xFFEDEA99),) : "Primrose",
    ColorValueVo( Color(0xFFEDF5DD),) : "Frost",
    ColorValueVo( Color(0xFFEDF5F5),) : "Aqua Haze",
    ColorValueVo( Color(0xFFEDF6FF),) : "Zumthor",
    ColorValueVo( Color(0xFFEDF9F1),) : "Narvik",
    ColorValueVo( Color(0xFFEDFC84),) : "Honeysuckle",
    ColorValueVo( Color(0xFFEE82EE),) : "Lavender Magenta",
    ColorValueVo( Color(0xFFEEC1BE),) : "Beauty Bush",
    ColorValueVo( Color(0xFFEED794),) : "Chalky",
    ColorValueVo( Color(0xFFEED9C4),) : "Almond",
    ColorValueVo( Color(0xFFEEDC82),) : "Flax",
    ColorValueVo( Color(0xFFEEDEDA),) : "Bizarre",
    ColorValueVo( Color(0xFFEEE3AD),) : "Double Colonial White",
    ColorValueVo( Color(0xFFEEEEE8),) : "Cararra",
    ColorValueVo( Color(0xFFEEEF78),) : "Manz",
    ColorValueVo( Color(0xFFEEF0C8),) : "Tahuna Sands",
    ColorValueVo( Color(0xFFEEF0F3),) : "Athens Gray",
    ColorValueVo( Color(0xFFEEF3C3),) : "Tusk",
    ColorValueVo( Color(0xFFEEF4DE),) : "Loafer",
    ColorValueVo( Color(0xFFEEF6F7),) : "Catskill White",
    ColorValueVo( Color(0xFFEEFDFF),) : "Twilight Blue",
    ColorValueVo( Color(0xFFEEFF9A),) : "Jonquil",
    ColorValueVo( Color(0xFFEEFFE2),) : "Rice Flower",
    ColorValueVo( Color(0xFFEF863F),) : "Jaffa",
    ColorValueVo( Color(0xFFEFEFEF),) : "Gallery",
    ColorValueVo( Color(0xFFEFF2F3),) : "Porcelain",
    ColorValueVo( Color(0xFFF091A9),) : "Mauvelous",
    ColorValueVo( Color(0xFFF0D52D),) : "Golden Dream",
    ColorValueVo( Color(0xFFF0DB7D),) : "Golden Sand",
    ColorValueVo( Color(0xFFF0DC82),) : "Buff",
    ColorValueVo( Color(0xFFF0E2EC),) : "Prim",
    ColorValueVo( Color(0xFFF0E68C),) : "Khaki",
    ColorValueVo( Color(0xFFF0EEFD),) : "Selago",
    ColorValueVo( Color(0xFFF0EEFF),) : "Titan White",
    ColorValueVo( Color(0xFFF0F8FF),) : "Alice Blue",
    ColorValueVo( Color(0xFFF0FCEA),) : "Feta",
    ColorValueVo( Color(0xFFF18200),) : "Gold Drop",
    ColorValueVo( Color(0xFFF19BAB),) : "Wewak",
    ColorValueVo( Color(0xFFF1E788),) : "Sahara Sand",
    ColorValueVo( Color(0xFFF1E9D2),) : "Parchment",
    ColorValueVo( Color(0xFFF1E9FF),) : "Blue Chalk",
    ColorValueVo( Color(0xFFF1EEC1),) : "Mint Julep",
    ColorValueVo( Color(0xFFF1F1F1),) : "Seashell",
    ColorValueVo( Color(0xFFF1F7F2),) : "Saltpan",
    ColorValueVo( Color(0xFFF1FFAD),) : "Tidal",
    ColorValueVo( Color(0xFFF1FFC8),) : "Chiffon",
    ColorValueVo( Color(0xFFF2552A),) : "Flamingo",
    ColorValueVo( Color(0xFFF28500),) : "Tangerine",
    ColorValueVo( Color(0xFFF2C3B2),) : "Mandys Pink",
    ColorValueVo( Color(0xFFF2F2F2),) : "Concrete",
    ColorValueVo( Color(0xFFF2FAFA),) : "Black Squeeze",
    ColorValueVo( Color(0xFFF34723),) : "Pomegranate",
    ColorValueVo( Color(0xFFF3AD16),) : "Buttercup",
    ColorValueVo( Color(0xFFF3D69D),) : "New Orleans",
    ColorValueVo( Color(0xFFF3D9DF),) : "Vanilla Ice",
    ColorValueVo( Color(0xFFF3E7BB),) : "Sidecar",
    ColorValueVo( Color(0xFFF3E9E5),) : "Dawn Pink",
    ColorValueVo( Color(0xFFF3EDCF),) : "Wheatfield",
    ColorValueVo( Color(0xFFF3FB62),) : "Canary",
    ColorValueVo( Color(0xFFF3FBD4),) : "Orinoco",
    ColorValueVo( Color(0xFFF3FFD8),) : "Carla",
    ColorValueVo( Color(0xFFF400A1),) : "Hollywood Cerise",
    ColorValueVo( Color(0xFFF4A460),) : "Sandy brown",
    ColorValueVo( Color(0xFFF4C430),) : "Saffron",
    ColorValueVo( Color(0xFFF4D81C),) : "Ripe Lemon",
    ColorValueVo( Color(0xFFF4EBD3),) : "Janna",
    ColorValueVo( Color(0xFFF4F2EE),) : "Pampas",
    ColorValueVo( Color(0xFFF4F4F4),) : "Wild Sand",
    ColorValueVo( Color(0xFFF4F8FF),) : "Zircon",
    ColorValueVo( Color(0xFFF57584),) : "Froly",
    ColorValueVo( Color(0xFFF5C85C),) : "Cream Can",
    ColorValueVo( Color(0xFFF5C999),) : "Manhattan",
    ColorValueVo( Color(0xFFF5D5A0),) : "Maize",
    ColorValueVo( Color(0xFFF5DEB3),) : "Wheat",
    ColorValueVo( Color(0xFFF5E7A2),) : "Sandwisp",
    ColorValueVo( Color(0xFFF5E7E2),) : "Pot Pourri",
    ColorValueVo( Color(0xFFF5E9D3),) : "Albescent White",
    ColorValueVo( Color(0xFFF5EDEF),) : "Soft Peach",
    ColorValueVo( Color(0xFFF5F3E5),) : "Ecru White",
    ColorValueVo( Color(0xFFF5F5DC),) : "Beige",
    ColorValueVo( Color(0xFFF5FB3D),) : "Golden Fizz",
    ColorValueVo( Color(0xFFF5FFBE),) : "Australian Mint",
    ColorValueVo( Color(0xFFF64A8A),) : "French Rose",
    ColorValueVo( Color(0xFFF653A6),) : "Brilliant Rose",
    ColorValueVo( Color(0xFFF6A4C9),) : "Illusion",
    ColorValueVo( Color(0xFFF6F0E6),) : "Merino",
    ColorValueVo( Color(0xFFF6F7F7),) : "Black Haze",
    ColorValueVo( Color(0xFFF6FFDC),) : "Spring Sun",
    ColorValueVo( Color(0xFFF7468A),) : "Violet Red",
    ColorValueVo( Color(0xFFF77703),) : "Chilean Fire",
    ColorValueVo( Color(0xFFF77FBE),) : "Persian Pink",
    ColorValueVo( Color(0xFFF7B668),) : "Rajah",
    ColorValueVo( Color(0xFFF7C8DA),) : "Azalea",
    ColorValueVo( Color(0xFFF7DBE6),) : "We Peep",
    ColorValueVo( Color(0xFFF7F2E1),) : "Quarter Spanish White",
    ColorValueVo( Color(0xFFF7F5FA),) : "Whisper",
    ColorValueVo( Color(0xFFF7FAF7),) : "Snow Drift",
    ColorValueVo( Color(0xFFF8B853),) : "Casablanca",
    ColorValueVo( Color(0xFFF8C3DF),) : "Chantilly",
    ColorValueVo( Color(0xFFF8D9E9),) : "Cherub",
    ColorValueVo( Color(0xFFF8DB9D),) : "Marzipan",
    ColorValueVo( Color(0xFFF8DD5C),) : "Energy Yellow",
    ColorValueVo( Color(0xFFF8E4BF),) : "Givry",
    ColorValueVo( Color(0xFFF8F0E8),) : "White Linen",
    ColorValueVo( Color(0xFFF8F4FF),) : "Magnolia",
    ColorValueVo( Color(0xFFF8F6F1),) : "Spring Wood",
    ColorValueVo( Color(0xFFF8F7DC),) : "Coconut Cream",
    ColorValueVo( Color(0xFFF8F7FC),) : "White Lilac",
    ColorValueVo( Color(0xFFF8F8F7),) : "Desert Storm",
    ColorValueVo( Color(0xFFF8F99C),) : "Texas",
    ColorValueVo( Color(0xFFF8FACD),) : "Corn Field",
    ColorValueVo( Color(0xFFF8FDD3),) : "Mimosa",
    ColorValueVo( Color(0xFFF95A61),) : "Carnation",
    ColorValueVo( Color(0xFFF9BF58),) : "Saffron Mango",
    ColorValueVo( Color(0xFFF9E0ED),) : "Carousel Pink",
    ColorValueVo( Color(0xFFF9E4BC),) : "Dairy Cream",
    ColorValueVo( Color(0xFFF9E663),) : "Portica",
    ColorValueVo( Color(0xFFF9EAF3),) : "Amour",
    ColorValueVo( Color(0xFFF9F8E4),) : "Rum Swizzle",
    ColorValueVo( Color(0xFFF9FF8B),) : "Dolly",
    ColorValueVo( Color(0xFFF9FFF6),) : "Sugar Cane",
    ColorValueVo( Color(0xFFFA7814),) : "Ecstasy",
    ColorValueVo( Color(0xFFFA9D5A),) : "Tan Hide",
    ColorValueVo( Color(0xFFFAD3A2),) : "Corvette",
    ColorValueVo( Color(0xFFFADFAD),) : "Peach Yellow",
    ColorValueVo( Color(0xFFFAE600),) : "Turbo",
    ColorValueVo( Color(0xFFFAEAB9),) : "Astra",
    ColorValueVo( Color(0xFFFAECCC),) : "Champagne",
    ColorValueVo( Color(0xFFFAF0E6),) : "Linen",
    ColorValueVo( Color(0xFFFAF3F0),) : "Fantasy",
    ColorValueVo( Color(0xFFFAF7D6),) : "Citrine White",
    ColorValueVo( Color(0xFFFAFAFA),) : "Alabaster",
    ColorValueVo( Color(0xFFFAFDE4),) : "Hint of Yellow",
    ColorValueVo( Color(0xFFFAFFA4),) : "Milan",
    ColorValueVo( Color(0xFFFB607F),) : "Brink Pink",
    ColorValueVo( Color(0xFFFB8989),) : "Geraldine",
    ColorValueVo( Color(0xFFFBA0E3),) : "Lavender Rose",
    ColorValueVo( Color(0xFFFBA129),) : "Sea Buckthorn",
    ColorValueVo( Color(0xFFFBAC13),) : "Sun",
    ColorValueVo( Color(0xFFFBAED2),) : "Lavender Pink",
    ColorValueVo( Color(0xFFFBB2A3),) : "Rose Bud",
    ColorValueVo( Color(0xFFFBBEDA),) : "Cupid",
    ColorValueVo( Color(0xFFFBCCE7),) : "Classic Rose",
    ColorValueVo( Color(0xFFFBCEB1),) : "Apricot Peach",
    ColorValueVo( Color(0xFFFBE7B2),) : "Banana Mania",
    ColorValueVo( Color(0xFFFBE870),) : "Marigold Yellow",
    ColorValueVo( Color(0xFFFBE96C),) : "Festival",
    ColorValueVo( Color(0xFFFBEA8C),) : "Sweet Corn",
    ColorValueVo( Color(0xFFFBEC5D),) : "Candy Corn",
    ColorValueVo( Color(0xFFFBF9F9),) : "Hint of Red",
    ColorValueVo( Color(0xFFFBFFBA),) : "Shalimar",
    ColorValueVo( Color(0xFFFC0FC0),) : "Shocking Pink",
    ColorValueVo( Color(0xFFFC80A5),) : "Tickle Me Pink",
    ColorValueVo( Color(0xFFFC9C1D),) : "Tree Poppy",
    ColorValueVo( Color(0xFFFCC01E),) : "Lightning Yellow",
    ColorValueVo( Color(0xFFFCD667),) : "Goldenrod",
    ColorValueVo( Color(0xFFFCD917),) : "Candlelight",
    ColorValueVo( Color(0xFFFCDA98),) : "Cherokee",
    ColorValueVo( Color(0xFFFCF4D0),) : "Double Pearl Lusta",
    ColorValueVo( Color(0xFFFCF4DC),) : "Pearl Lusta",
    ColorValueVo( Color(0xFFFCF8F7),) : "Vista White",
    ColorValueVo( Color(0xFFFCFBF3),) : "Bianca",
    ColorValueVo( Color(0xFFFCFEDA),) : "Moon Glow",
    ColorValueVo( Color(0xFFFCFFE7),) : "China Ivory",
    ColorValueVo( Color(0xFFFCFFF9),) : "Ceramic",
    ColorValueVo( Color(0xFFFD0E35),) : "Torch Red",
    ColorValueVo( Color(0xFFFD5B78),) : "Wild Watermelon",
    ColorValueVo( Color(0xFFFD7B33),) : "Crusta",
    ColorValueVo( Color(0xFFFD7C07),) : "Sorbus",
    ColorValueVo( Color(0xFFFD9FA2),) : "Sweet Pink",
    ColorValueVo( Color(0xFFFDD5B1),) : "Light Apricot",
    ColorValueVo( Color(0xFFFDD7E4),) : "Pig Pink",
    ColorValueVo( Color(0xFFFDE1DC),) : "Cinderella",
    ColorValueVo( Color(0xFFFDE295),) : "Golden Glow",
    ColorValueVo( Color(0xFFFDE910),) : "Lemon",
    ColorValueVo( Color(0xFFFDF5E6),) : "Old Lace",
    ColorValueVo( Color(0xFFFDF6D3),) : "Half Colonial White",
    ColorValueVo( Color(0xFFFDF7AD),) : "Drover",
    ColorValueVo( Color(0xFFFDFEB8),) : "Pale Prim",
    ColorValueVo( Color(0xFFFDFFD5),) : "Cumulus",
    ColorValueVo( Color(0xFFFE28A2),) : "Persian Rose",
    ColorValueVo( Color(0xFFFE4C40),) : "Sunset Orange",
    ColorValueVo( Color(0xFFFE6F5E),) : "Bittersweet",
    ColorValueVo( Color(0xFFFE9D04),) : "California",
    ColorValueVo( Color(0xFFFEA904),) : "Yellow Sea",
    ColorValueVo( Color(0xFFFEBAAD),) : "Melon",
    ColorValueVo( Color(0xFFFED33C),) : "Bright Sun",
    ColorValueVo( Color(0xFFFED85D),) : "Dandelion",
    ColorValueVo( Color(0xFFFEDB8D),) : "Salomie",
    ColorValueVo( Color(0xFFFEE5AC),) : "Cape Honey",
    ColorValueVo( Color(0xFFFEEBF3),) : "Remy",
    ColorValueVo( Color(0xFFFEEFCE),) : "Oasis",
    ColorValueVo( Color(0xFFFEF0EC),) : "Bridesmaid",
    ColorValueVo( Color(0xFFFEF2C7),) : "Beeswax",
    ColorValueVo( Color(0xFFFEF3D8),) : "Bleach White",
    ColorValueVo( Color(0xFFFEF4CC),) : "Pipi",
    ColorValueVo( Color(0xFFFEF4DB),) : "Half Spanish White",
    ColorValueVo( Color(0xFFFEF4F8),) : "Wisp Pink",
    ColorValueVo( Color(0xFFFEF5F1),) : "Provincial Pink",
    ColorValueVo( Color(0xFFFEF7DE),) : "Half Dutch White",
    ColorValueVo( Color(0xFFFEF8E2),) : "Solitaire",
    ColorValueVo( Color(0xFFFEF8FF),) : "White Pointer",
    ColorValueVo( Color(0xFFFEF9E3),) : "Off Yellow",
    ColorValueVo( Color(0xFFFEFCED),) : "Orange White",
    ColorValueVo( Color(0xFFFF0000),) : "Red",
    ColorValueVo( Color(0xFFFF007F),) : "Rose",
    ColorValueVo( Color(0xFFFF00CC),) : "Purple Pizzazz",
    ColorValueVo( Color(0xFFFF00FF),) : "Magenta Fuchsia",
    ColorValueVo( Color(0xFFFF2400),) : "Scarlet",
    ColorValueVo( Color(0xFFFF3399),) : "Wild Strawberry",
    ColorValueVo( Color(0xFFFF33CC),) : "Razzle Dazzle Rose",
    ColorValueVo( Color(0xFFFF355E),) : "Radical Red",
    ColorValueVo( Color(0xFFFF3F34),) : "Red Orange",
    ColorValueVo( Color(0xFFFF4040),) : "Coral Red",
    ColorValueVo( Color(0xFFFF4D00),) : "Vermilion",
    ColorValueVo( Color(0xFFFF4F00),) : "International Orange",
    ColorValueVo( Color(0xFFFF6037),) : "Outrageous Orange",
    ColorValueVo( Color(0xFFFF6600),) : "Blaze Orange",
    ColorValueVo( Color(0xFFFF66FF),) : "Pink Flamingo",
    ColorValueVo( Color(0xFFFF681F),) : "Orange",
    ColorValueVo( Color(0xFFFF69B4),) : "Hot Pink",
    ColorValueVo( Color(0xFFFF6B53),) : "Persimmon",
    ColorValueVo( Color(0xFFFF6FFF),) : "Blush Pink",
    ColorValueVo( Color(0xFFFF7034),) : "Burning Orange",
    ColorValueVo( Color(0xFFFF7518),) : "Pumpkin",
    ColorValueVo( Color(0xFFFF7D07),) : "Flamenco",
    ColorValueVo( Color(0xFFFF7F00),) : "Flush Orange",
    ColorValueVo( Color(0xFFFF7F50),) : "Coral",
    ColorValueVo( Color(0xFFFF8C69),) : "Salmon",
    ColorValueVo( Color(0xFFFF9000),) : "Pizazz",
    ColorValueVo( Color(0xFFFF910F),) : "West Side",
    ColorValueVo( Color(0xFFFF91A4),) : "Pink Salmon",
    ColorValueVo( Color(0xFFFF9933),) : "Neon Carrot",
    ColorValueVo( Color(0xFFFF9966),) : "Atomic Tangerine",
    ColorValueVo( Color(0xFFFF9980),) : "Vivid Tangerine",
    ColorValueVo( Color(0xFFFF9E2C),) : "Sunshade",
    ColorValueVo( Color(0xFFFFA000),) : "Orange Peel",
    ColorValueVo( Color(0xFFFFA194),) : "Mona Lisa",
    ColorValueVo( Color(0xFFFFA500),) : "Web Orange",
    ColorValueVo( Color(0xFFFFA6C9),) : "Carnation Pink",
    ColorValueVo( Color(0xFFFFAB81),) : "Hit Pink",
    ColorValueVo( Color(0xFFFFAE42),) : "Yellow Orange",
    ColorValueVo( Color(0xFFFFB0AC),) : "Cornflower Lilac",
    ColorValueVo( Color(0xFFFFB1B3),) : "Sundown",
    ColorValueVo( Color(0xFFFFB31F),) : "My Sin",
    ColorValueVo( Color(0xFFFFB555),) : "Texas Rose",
    ColorValueVo( Color(0xFFFFB7D5),) : "Cotton Candy",
    ColorValueVo( Color(0xFFFFB97B),) : "Macaroni and Cheese",
    ColorValueVo( Color(0xFFFFBA00),) : "Selective Yellow",
    ColorValueVo( Color(0xFFFFBD5F),) : "Koromiko",
    ColorValueVo( Color(0xFFFFBF00),) : "Amber",
    ColorValueVo( Color(0xFFFFC0A8),) : "Wax Flower",
    ColorValueVo( Color(0xFFFFC0CB),) : "Pink",
    ColorValueVo( Color(0xFFFFC3C0),) : "Your Pink",
    ColorValueVo( Color(0xFFFFC901),) : "Supernova",
    ColorValueVo( Color(0xFFFFCBA4),) : "Flesh",
    ColorValueVo( Color(0xFFFFCC33),) : "Sunglow",
    ColorValueVo( Color(0xFFFFCC5C),) : "Golden Tainoi",
    ColorValueVo( Color(0xFFFFCC99),) : "Peach Orange",
    ColorValueVo( Color(0xFFFFCD8C),) : "Chardonnay",
    ColorValueVo( Color(0xFFFFD1DC),) : "Pastel Pink",
    ColorValueVo( Color(0xFFFFD2B7),) : "Romantic",
    ColorValueVo( Color(0xFFFFD38C),) : "Grandis",
    ColorValueVo( Color(0xFFFFD700),) : "Gold",
    ColorValueVo( Color(0xFFFFD800),) : "School bus Yellow",
    ColorValueVo( Color(0xFFFFD8D9),) : "Cosmos",
    ColorValueVo( Color(0xFFFFDB58),) : "Mustard",
    ColorValueVo( Color(0xFFFFDCD6),) : "Peach Schnapps",
    ColorValueVo( Color(0xFFFFDDAF),) : "Caramel",
    ColorValueVo( Color(0xFFFFDDCD),) : "Tuft Bush",
    ColorValueVo( Color(0xFFFFDDCF),) : "Watusi",
    ColorValueVo( Color(0xFFFFDDF4),) : "Pink Lace",
    ColorValueVo( Color(0xFFFFDEAD),) : "Navajo White",
    ColorValueVo( Color(0xFFFFDEB3),) : "Frangipani",
    ColorValueVo( Color(0xFFFFE1DF),) : "Pippin",
    ColorValueVo( Color(0xFFFFE1F2),) : "Pale Rose",
    ColorValueVo( Color(0xFFFFE2C5),) : "Negroni",
    ColorValueVo( Color(0xFFFFE5A0),) : "Cream Brulee",
    ColorValueVo( Color(0xFFFFE5B4),) : "Peach",
    ColorValueVo( Color(0xFFFFE6C7),) : "Tequila",
    ColorValueVo( Color(0xFFFFE772),) : "Kournikova",
    ColorValueVo( Color(0xFFFFEAC8),) : "Sandy Beach",
    ColorValueVo( Color(0xFFFFEAD4),) : "Karry",
    ColorValueVo( Color(0xFFFFEC13),) : "Broom",
    ColorValueVo( Color(0xFFFFEDBC),) : "Colonial White",
    ColorValueVo( Color(0xFFFFEED8),) : "Derby",
    ColorValueVo( Color(0xFFFFEFA1),) : "Vis Vis",
    ColorValueVo( Color(0xFFFFEFC1),) : "Egg White",
    ColorValueVo( Color(0xFFFFEFD5),) : "Papaya Whip",
    ColorValueVo( Color(0xFFFFEFEC),) : "Fair Pink",
    ColorValueVo( Color(0xFFFFF0DB),) : "Peach Cream",
    ColorValueVo( Color(0xFFFFF0F5),) : "Lavender blush",
    ColorValueVo( Color(0xFFFFF14F),) : "Gorse",
    ColorValueVo( Color(0xFFFFF1B5),) : "Buttermilk",
    ColorValueVo( Color(0xFFFFF1D8),) : "Pink Lady",
    ColorValueVo( Color(0xFFFFF1EE),) : "Forget Me Not",
    ColorValueVo( Color(0xFFFFF1F9),) : "Tutu",
    ColorValueVo( Color(0xFFFFF39D),) : "Picasso",
    ColorValueVo( Color(0xFFFFF3F1),) : "Chardon",
    ColorValueVo( Color(0xFFFFF46E),) : "Paris Daisy",
    ColorValueVo( Color(0xFFFFF4CE),) : "Barley White",
    ColorValueVo( Color(0xFFFFF4DD),) : "Egg Sour",
    ColorValueVo( Color(0xFFFFF4E0),) : "Sazerac",
    ColorValueVo( Color(0xFFFFF4E8),) : "Serenade",
    ColorValueVo( Color(0xFFFFF4F3),) : "Chablis",
    ColorValueVo( Color(0xFFFFF5EE),) : "Seashell Peach",
    ColorValueVo( Color(0xFFFFF5F3),) : "Sauvignon",
    ColorValueVo( Color(0xFFFFF6D4),) : "Milk Punch",
    ColorValueVo( Color(0xFFFFF6DF),) : "Varden",
    ColorValueVo( Color(0xFFFFF6F5),) : "Rose White",
    ColorValueVo( Color(0xFFFFF8D1),) : "Baja White",
    ColorValueVo( Color(0xFFFFF9E2),) : "Gin Fizz",
    ColorValueVo( Color(0xFFFFF9E6),) : "Early Dawn",
    ColorValueVo( Color(0xFFFFFACD),) : "Lemon Chiffon",
    ColorValueVo( Color(0xFFFFFAF4),) : "Bridal Heath",
    ColorValueVo( Color(0xFFFFFBDC),) : "Scotch Mist",
    ColorValueVo( Color(0xFFFFFBF9),) : "Soapstone",
    ColorValueVo( Color(0xFFFFFC99),) : "Witch Haze",
    ColorValueVo( Color(0xFFFFFCEA),) : "Buttery White",
    ColorValueVo( Color(0xFFFFFCEE),) : "Island Spice",
    ColorValueVo( Color(0xFFFFFDD0),) : "Cream",
    ColorValueVo( Color(0xFFFFFDE6),) : "Chilean Heath",
    ColorValueVo( Color(0xFFFFFDE8),) : "Travertine",
    ColorValueVo( Color(0xFFFFFDF3),) : "Orchid White",
    ColorValueVo( Color(0xFFFFFDF4),) : "Quarter Pearl Lusta",
    ColorValueVo( Color(0xFFFFFEE1),) : "Half and Half",
    ColorValueVo( Color(0xFFFFFEEC),) : "Apricot White",
    ColorValueVo( Color(0xFFFFFEF0),) : "Rice Cake",
    ColorValueVo( Color(0xFFFFFEF6),) : "Black White",
    ColorValueVo( Color(0xFFFFFEFD),) : "Romance",
    ColorValueVo( Color(0xFFFFFF00),) : "Yellow",
    ColorValueVo( Color(0xFFFFFF66),) : "Laser Lemon",
    ColorValueVo( Color(0xFFFFFF99),) : "Pale Canary",
    ColorValueVo( Color(0xFFFFFFB4),) : "Portafino",
    ColorValueVo( Color(0xFFFFFFF0),) : "Ivory",
    ColorValueVo( Color(0xFFFFFFFF),) : "White",
  };
}